# -*- coding: utf-8 -*-
"""Club Best Shot & Eyes closure.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ZeY61NvY2ZH-zQj5Z08YlpB9m76gLoq

## Best shot
"""

# ================================
# CELL 1) Install + Imports; same
# ================================
!pip -q install -U openai pillow pandas tqdm openpyxl

import os
import io
import re
import json
import base64
import shutil
import zipfile
import datetime
from typing import List

import pandas as pd
from PIL import Image, ExifTags
from tqdm import tqdm

from google.colab import files, userdata, drive
from openai import OpenAI
from IPython.display import display
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows

print("OK")

# =========================
# CELL 2-2) Setup
# =========================

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
client = OpenAI(api_key=OPENAI_API_KEY)

MODEL_NAME = "gpt-5.4"

UPLOAD_BESTPHOTO_DIR = "/content/ocr_bestphoto_uploads"
OUT_BESTPHOTO_DIR    = "/content/ocr_bestphoto_outputs"
os.makedirs(UPLOAD_BESTPHOTO_DIR, exist_ok=True)
os.makedirs(OUT_BESTPHOTO_DIR, exist_ok=True)

# Grouping config
GROUPING_MODE = "auto_adjacent_gpt"
GROUP_SIZES = [4, 3]
FIXED_GROUP_SIZE = 4
TREAT_LOW_CONF_BOUNDARY_AS_SAME = True
STRICT_FORMALITY_REJECTION = True

# File naming config
RANK_PAD = 2
FORCE_GROUP_PREFIX = False
CLUB_BEST_TOKEN = "本"

print("Folders:", UPLOAD_BESTPHOTO_DIR, OUT_BESTPHOTO_DIR)
print("Model:", MODEL_NAME)
print("Grouping mode:", GROUPING_MODE)

def get_file_date_string(path: str) -> str:
    # 1) Try EXIF DateTimeOriginal
    try:
        img = Image.open(path)
        exif = img._getexif()
        if exif:
            for tag_id, value in exif.items():
                tag = ExifTags.TAGS.get(tag_id, tag_id)
                if tag == "DateTimeOriginal" and value:
                    # Format: "YYYY:MM:DD HH:MM:SS" -> "YYYYMMDD"
                    return str(value)[:10].replace(":", "")
    except Exception:
        pass

    # 2) Fallback to file modified date if EXIF is missing
    try:
        mod_time = os.path.getmtime(path)
        return datetime.datetime.fromtimestamp(mod_time).strftime("%Y%m%d")
    except Exception:
        return "00000000"

# 1) Mount Google Drive
drive.mount("/content/drive")

# 2) Define source folder in Drive (CHANGE THIS PATH)
DRIVE_SOURCE_FOLDER = "/content/drive/MyDrive/LTID/Club/01_Club - small"

# 3) Copy files into processing folder
if os.path.exists(DRIVE_SOURCE_FOLDER):
    exts = (".png", ".jpg", ".jpeg", ".webp", ".bmp", ".tif", ".tiff")
    found_count = 0
    for root, _, filenames in os.walk(DRIVE_SOURCE_FOLDER):
        for f in filenames:
            if f.lower().endswith(exts):
                src = os.path.join(root, f)
                dst = os.path.join(UPLOAD_BESTPHOTO_DIR, f)
                shutil.copy2(src, dst)
                found_count += 1

    image_paths = sorted(
        [
            os.path.join(UPLOAD_BESTPHOTO_DIR, f)
            for f in os.listdir(UPLOAD_BESTPHOTO_DIR)
            if f.lower().endswith(exts)
        ]
    )
    print(f"Successfully loaded {found_count} images from Drive.")
    print(f"Total images in upload directory: {len(image_paths)}")
else:
    print(f"Error: Source folder {DRIVE_SOURCE_FOLDER} not found. Please check the path.")
    image_paths = []

"""Don't run this cell (3-2) if you already loaded the images from Google Drive"""

# ==========================================
# CELL 3-2) Upload photos (and ZIP) like OCR2
# ==========================================
def ensure_dir(d):
    os.makedirs(d, exist_ok=True)

def upload_images_to_folder(dst_dir: str) -> List[str]:
    ensure_dir(dst_dir)
    uploaded = files.upload()

    # Move/extract into dst_dir
    for fn in uploaded.keys():
        src = f"/content/{fn}"

        if fn.lower().endswith(".zip"):
            with zipfile.ZipFile(src, "r") as z:
                z.extractall(dst_dir)
            os.remove(src)
        else:
            shutil.move(src, os.path.join(dst_dir, fn))

    # Collect image paths (recursive, because zip may contain subfolders)
    exts = (".png", ".jpg", ".jpeg", ".webp", ".bmp", ".tif", ".tiff")
    image_paths = []
    for root, _, files_ in os.walk(dst_dir):
        for f in files_:
            if f.lower().endswith(exts):
                image_paths.append(os.path.join(root, f))

    image_paths = sorted(image_paths)
    print(f"Uploaded images found: {len(image_paths)}")
    if len(image_paths) > 0:
        print("Example:", image_paths[0])
    return image_paths

image_paths = upload_images_to_folder(UPLOAD_BESTPHOTO_DIR)

# ==========================================
# CELL 4) GPT-5 OCR (NO preprocessing); same
# ==========================================
def encode_image_path_to_base64(path: str) -> str:
    # Convert to RGB JPEG in-memory for stable sending
    img = Image.open(path).convert("RGB")
    buf = io.BytesIO()
    img.save(buf, format="JPEG", quality=95)
    return base64.b64encode(buf.getvalue()).decode("utf-8")


def call_gpt5_image_json(client: OpenAI, base64_image: str, prompt: str, model: str) -> str:
    messages = [
        {
            "role": "user",
            "content": [
                {"type": "input_text", "text": prompt},
                {
                    "type": "input_image",
                    "image_url": f"data:image/jpeg;base64,{base64_image}",
                    "detail": "high",
                },
            ],
        }
    ]

    resp = client.responses.create(
        model=model,
        input=messages,
        reasoning={"effort": "medium"},
    )
    return resp.output_text


def call_gpt5_two_images_json(
    client: OpenAI,
    base64_image_a: str,
    base64_image_b: str,
    prompt: str,
    model: str,
) -> str:
    messages = [
        {
            "role": "user",
            "content": [
                {"type": "input_text", "text": prompt},
                {
                    "type": "input_image",
                    "image_url": f"data:image/jpeg;base64,{base64_image_a}",
                    "detail": "high",
                },
                {
                    "type": "input_image",
                    "image_url": f"data:image/jpeg;base64,{base64_image_b}",
                    "detail": "high",
                },
            ],
        }
    ]

    resp = client.responses.create(
        model=model,
        input=messages,
        reasoning={"effort": "medium"},
    )
    return resp.output_text


def parse_json_object(text: str) -> dict:
    if not text:
        raise ValueError("Empty model response")

    cleaned = text.strip()

    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?", "", cleaned.strip(), flags=re.IGNORECASE).strip()
        cleaned = re.sub(r"```$", "", cleaned.strip()).strip()

    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        start = cleaned.find("{")
        end = cleaned.rfind("}")
        if start != -1 and end != -1 and end > start:
            return json.loads(cleaned[start : end + 1])
        raise

GROUP_BOUNDARY_PROMPT = """
You are comparing TWO consecutive group photos from the same shooting day.

Image 1 appears first in the sequence, Image 2 appears immediately after it.

Task:
- Decide whether Image 1 and Image 2 belong to the SAME group of people.

Definition of same group:
- Mostly the same students/people are present (small pose changes are OK).
- Clothing/background variations are allowed if clearly same people.

Definition of different group:
- Clearly different people/team/class, meaning this is a boundary between groups.

OUTPUT FORMAT (STRICT JSON ONLY):
{
    "same_group": true | false,
    "confidence": "high" | "medium" | "low",
    "reason": "one short sentence"
}

Rules:
- Set is_ng=true ONLY for clear, severe defects that make the photo unusable.
- If issues are minor, keep is_ng=false and reflect quality by lower scores/comments.
- Be professional and consistent.
- Output JSON only. No explanations.
""".strip()

PHOTO_EVAL_PROMPT = """
You are a professional photo editor selecting the best shot for a graduation album.

Evaluate the photo using the criteria below.

CRITERIA:

1) Formality & Suitability (CRITICAL)
   - Standard posture (straight, facing forward).
   - Natural, professional expression (natural smile or neutral is best).
   - NO hand gestures (e.g., peace signs, hearts, thumbs up).
   - Subject placement balance: person centered, head not cut off, balanced framing.

2) Beauty & Technical Quality
   - Lighting: Bright, clear, NO blown-out highlights or heavy shadows.
   - Technical: Sharp focus, NO camera shake or motion blur.
   - Colorfulness and sense of depth.

3) Expression & Emotion
   - Eyes: Eyes must be open (blink check).
   - Face Visibility: Face must be clearly visible (not obscured or barely visible).
   - Natural expression and emotional appeal.

4) NG (Must eliminate if ANY apply)
   - Blur, out of focus, or visible camera shake.
   - Eyes closed (blinking).
   - Blown-out highlights or severe exposure issues.
   - Face is barely visible or obscured.
   - Subject failing, stumbling, or falling.
   - Eating or mouth full.
   - Strange or obscene posing.
   - Severe framing issues (head cut off, poor balance).

OUTPUT FORMAT (STRICT JSON ONLY):
{
    "formality_score": 0-10,
    "beauty_score": 0-10,
    "expression_score": 0-10,
    "emotion_score": 0-10,
    "has_hand_gesture": true | false,
    "has_exaggerated_expression": true | false,
    "eyes_closed": true | false,
    "face_obscured": true | false,
    "gesture_expression_penalty": 0-5,
    "is_ng": true | false,
    "ng_reason": "string or null",
    "short_comment": "one-sentence professional comment"
}

Rules:
- Set is_ng=true for eyes closed, severe camera shake, or obscured faces.
- If visible hand gestures or clearly exaggerated laughing/posing appear,
    set the corresponding flags and apply a meaningful penalty.
- Be professional and consistent.
- Output JSON only. No explanations.
""".strip()

# ==========================================
# CELL 6) Group images by sequence
# ==========================================
def chunk_list(items: List[str], size: int) -> List[List[str]]:
    if size <= 0:
        raise ValueError("FIXED_GROUP_SIZE must be > 0")
    return [items[i : i + size] for i in range(0, len(items), size)]


def detect_adjacent_same_group(prev_path: str, curr_path: str):
    try:
        b64_prev = encode_image_path_to_base64(prev_path)
        b64_curr = encode_image_path_to_base64(curr_path)
        raw = call_gpt5_two_images_json(
            client,
            b64_prev,
            b64_curr,
            GROUP_BOUNDARY_PROMPT,
            MODEL_NAME,
        )
        data = parse_json_object(raw)

        same_group = bool(data.get("same_group", True))
        confidence = str(data.get("confidence", "low")).lower()
        reason = data.get("reason", "")
        adjusted = False

        # Avoid over-splitting when the boundary confidence is weak.
        if (not same_group) and confidence == "low" and TREAT_LOW_CONF_BOUNDARY_AS_SAME:
            same_group = True
            adjusted = True
            reason = "Low-confidence boundary was treated as same group."

        return same_group, confidence, reason, adjusted

    except Exception as e:
        # Fail-safe: keep same group to avoid accidental split from transient API issues.
        return True, "low", f"Boundary check failed: {e}", True


def build_groups_auto_adjacent(image_paths: List[str]):
    if not image_paths:
        return [], []

    if len(image_paths) == 1:
        return [image_paths], []

    groups = []
    decisions = []
    current_group = [image_paths[0]]

    for i in tqdm(range(1, len(image_paths)), desc="Auto grouping"):
        prev_path = image_paths[i - 1]
        curr_path = image_paths[i]

        same_group, confidence, reason, adjusted = detect_adjacent_same_group(prev_path, curr_path)

        decisions.append(
            {
                "pair_index": i,
                "prev_file": os.path.basename(prev_path),
                "curr_file": os.path.basename(curr_path),
                "same_group": same_group,
                "confidence": confidence,
                "adjusted": adjusted,
                "reason": reason,
            }
        )

        if same_group:
            current_group.append(curr_path)
        else:
            groups.append(current_group)
            current_group = [curr_path]

    groups.append(current_group)
    return groups, decisions


def build_groups(image_paths: List[str]) -> List[List[str]]:
    if not image_paths:
        return []

    if GROUPING_MODE == "all_in_one":
        return [image_paths]

    if GROUPING_MODE == "auto_adjacent_gpt":
        groups_auto, decisions = build_groups_auto_adjacent(image_paths)
        globals()["auto_group_decisions"] = decisions
        return groups_auto

    if GROUPING_MODE == "fixed_size":
        return chunk_list(image_paths, FIXED_GROUP_SIZE)

    if GROUPING_MODE == "sizes":
        groups = []
        cursor = 0

        for n in GROUP_SIZES:
            if n <= 0:
                continue
            if cursor >= len(image_paths):
                break
            groups.append(image_paths[cursor : cursor + n])
            cursor += n

        if cursor < len(image_paths):
            groups.append(image_paths[cursor:])
            print(
                "Warning: GROUP_SIZES did not cover all images. "
                f"Added trailing group with {len(image_paths[cursor:])} image(s)."
            )

        return [g for g in groups if g]

    raise ValueError("GROUPING_MODE must be one of: sizes, fixed_size, all_in_one, auto_adjacent_gpt")


auto_group_decisions = []
groups = build_groups(image_paths)

print("\n" + "=" * 60)
print("GROUP SUMMARY")
print("=" * 60)
print(f"Total images: {len(image_paths)}")
print(f"Detected groups: {len(groups)}")
for idx, g in enumerate(groups, start=1):
    print(f"  Group {idx}: {len(g)} image(s)")

if GROUPING_MODE == "auto_adjacent_gpt" and auto_group_decisions:
    print("\nAuto grouping decisions:")
    display(pd.DataFrame(auto_group_decisions))

# ==========================================
# CELL 7) Evaluate and rank each group (Updated with client criteria)
# ==========================================
def empty_eval_df() -> pd.DataFrame:
    return pd.DataFrame(
        columns=[
            "formality_score",
            "beauty_score",
            "expression_score",
            "emotion_score",
            "has_hand_gesture",
            "has_exaggerated_expression",
            "eyes_closed",
            "face_obscured",
            "gesture_expression_penalty",
            "is_ng",
            "ng_reason",
            "short_comment",
            "file_name",
            "path",
            "group_index",
        ]
    )

def calculate_rankings(df_eval, group_idx, allow_formality_issues=False):
    df_temp = df_eval.copy()

    # Strict rejection logic updated to include new client-requested flags
    if STRICT_FORMALITY_REJECTION and not allow_formality_issues:
        gesture_mask = df_temp["has_hand_gesture"] == True
        laugh_mask = df_temp["has_exaggerated_expression"] == True
        eyes_mask = df_temp["eyes_closed"] == True
        face_mask = df_temp["face_obscured"] == True
        df_temp.loc[gesture_mask | laugh_mask | eyes_mask | face_mask, "is_ng"] = True

    df_ok = df_temp[df_temp["is_ng"] == False].copy()

    if df_ok.empty:
        return df_ok

    for col in ["formality_score", "beauty_score", "expression_score", "emotion_score", "gesture_expression_penalty"]:
        df_ok[col] = pd.to_numeric(df_ok[col], errors="coerce").fillna(0)

    df_ok["rule_penalty"] = (
        df_ok["gesture_expression_penalty"] * 0.7
        + df_ok["has_hand_gesture"].astype(int) * 2.0
        + df_ok["has_exaggerated_expression"].astype(int) * 1.5
    )

    # Fixed the indexing error here
    df_ok["total_score"] = (
        df_ok["formality_score"] * 0.35
        + df_ok["beauty_score"] * 0.30
        + df_ok["expression_score"] * 0.20
        + df_ok["emotion_score"] * 0.15
        - df_ok["rule_penalty"]
    )

    df_ok = df_ok.sort_values("total_score", ascending=False).reset_index(drop=True)
    df_ok["rank"] = range(1, len(df_ok) + 1)
    return df_ok

all_group_results = []

for group_idx, group_paths in enumerate(groups, start=1):
    print(f"\n{'-' * 50}\nProcessing group {group_idx} ({len(group_paths)} photos)")
    photo_evals = []
    for p in tqdm(group_paths, desc=f"Group {group_idx} eval"):
        try:
            b64 = encode_image_path_to_base64(p)
            raw_resp = call_gpt5_image_json(client, b64, PHOTO_EVAL_PROMPT, MODEL_NAME)
            data = parse_json_object(raw_resp)
            photo_evals.append({
                "formality_score": data.get("formality_score"),
                "beauty_score": data.get("beauty_score"),
                "expression_score": data.get("expression_score"),
                "emotion_score": data.get("emotion_score"),
                "has_hand_gesture": bool(data.get("has_hand_gesture", False)),
                "has_exaggerated_expression": bool(data.get("has_exaggerated_expression", False)),
                "eyes_closed": bool(data.get("eyes_closed", False)),
                "face_obscured": bool(data.get("face_obscured", False)),
                "gesture_expression_penalty": data.get("gesture_expression_penalty", 0),
                "is_ng": bool(data.get("is_ng", False)),
                "ng_reason": data.get("ng_reason"),
                "short_comment": data.get("short_comment"),
                "file_name": os.path.basename(p),
                "path": p, "group_index": group_idx
            })
        except Exception as e:
            photo_evals.append({"is_ng": True, "ng_reason": str(e), "file_name": os.path.basename(p), "path": p, "group_index": group_idx})

    df_eval = pd.DataFrame(photo_evals) if photo_evals else empty_eval_df()
    df_rank = calculate_rankings(df_eval, group_idx, allow_formality_issues=False)

    if df_rank.empty and not df_eval.empty:
        print(f"Group {group_idx}: Relaxing rules to pick best available.")
        df_rank = calculate_rankings(df_eval, group_idx, allow_formality_issues=True)

    all_group_results.append({"group_index": group_idx, "group_paths": group_paths, "df_eval": df_eval, "df_rank": df_rank})
    if not df_rank.empty:
        display(df_rank[["rank", "file_name", "total_score", "eyes_closed", "short_comment"]])

# ==========================================
# CELL 8) Save ONE Excel + ONE flat ranked folder + ZIP
# ==========================================
def safe_concat(dfs: List[pd.DataFrame], default_cols=None) -> pd.DataFrame:
    valid = []
    for df in dfs:
        if isinstance(df, pd.DataFrame) and len(df.columns) > 0 and len(df) > 0:
            valid.append(df)
    if valid:
        return pd.concat(valid, ignore_index=True)
    return pd.DataFrame(columns=default_cols or [])


def unique_path(path: str) -> str:
    if not os.path.exists(path):
        return path
    base, ext = os.path.splitext(path)
    k = 2
    while True:
        candidate = f"{base}__dup{k}{ext}"
        if not os.path.exists(candidate):
            return candidate
        k += 1


def write_df_to_worksheet(ws, df: pd.DataFrame):
    if df is None or not isinstance(df, pd.DataFrame):
        df = pd.DataFrame()

    df_to_write = df.copy()
    for col in df_to_write.columns:
        df_to_write[col] = df_to_write[col].apply(
            lambda x: "" if pd.isna(x) else str(x) if isinstance(x, (list, dict, tuple, set)) else x
        )

    for row in dataframe_to_rows(df_to_write, index=False, header=True):
        ws.append(row)

    for col_cells in ws.columns:
        col_letter = col_cells[0].column_letter
        max_len = 0
        for cell in col_cells:
            try:
                cell_len = len(str(cell.value)) if cell.value is not None else 0
                if cell_len > max_len:
                    max_len = cell_len
            except Exception:
                pass
        ws.column_dimensions[col_letter].width = min(max_len + 2, 40)


ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
os.makedirs(OUT_BESTPHOTO_DIR, exist_ok=True)

RANKED_OUTPUT_DIR = os.path.join(OUT_BESTPHOTO_DIR, f"{ts}_ranked_photos")
os.makedirs(RANKED_OUTPUT_DIR, exist_ok=True)

summary_rows = []
rename_rows = []
combined_eval = []
combined_rank = []

for result in all_group_results:
    group_index = result["group_index"]
    df_eval = result.get("df_eval", pd.DataFrame())
    df_rank = result.get("df_rank", pd.DataFrame())
    best = result.get("best_result", {})

    combined_eval.append(df_eval if isinstance(df_eval, pd.DataFrame) else pd.DataFrame())
    combined_rank.append(df_rank if isinstance(df_rank, pd.DataFrame) else pd.DataFrame())

    copied = 0
    failed = []

    if isinstance(df_rank, pd.DataFrame) and not df_rank.empty:
        for _, row in df_rank.iterrows():
            src_path = row["path"]
            rank = int(row["rank"])
            original_file_name = row["file_name"]
            stem, ext = os.path.splitext(original_file_name)
            date_prefix = get_file_date_string(src_path)

            new_name = f"{date_prefix}_{stem}_{CLUB_BEST_TOKEN}{rank:0{RANK_PAD}d}{ext}"

            if FORCE_GROUP_PREFIX:
                new_name = f"G{group_index:02d}_{new_name}"

            if src_path and os.path.exists(src_path):
                dst_path = unique_path(os.path.join(RANKED_OUTPUT_DIR, new_name))
                shutil.copy2(src_path, dst_path)
                copied += 1

                rename_rows.append(
                    {
                        "group_index": group_index,
                        "rank": rank,
                        "original_file_name": original_file_name,
                        "original_path": src_path,
                        "new_file_name": os.path.basename(dst_path),
                        "total_score": row.get("total_score"),
                    }
                )
            else:
                failed.append(row["file_name"])

    summary_rows.append(
        {
            "group_index": group_index,
            "input_count": len(result.get("group_paths", [])),
            "ranked_count": len(df_rank) if isinstance(df_rank, pd.DataFrame) else 0,
            "copied_count": copied,
            "best_file_name": best.get("best_file_name"),
            "best_reason": best.get("reason"),
            "copy_failures": " | ".join(failed),
        }
    )

    print(f"\nGroup {group_index} copied files: {copied}")
    if failed:
        print(f"Missing files: {failed[:10]}")
        if len(failed) > 10:
            print(f"... and {len(failed) - 10} more")


df_summary = pd.DataFrame(summary_rows)
df_rename = pd.DataFrame(rename_rows)
df_combined_eval = safe_concat(combined_eval)
df_combined_rank = safe_concat(combined_rank)

if not df_rename.empty:
    df_rename = df_rename.sort_values(["group_index", "rank"]).reset_index(drop=True)

excel_path = os.path.join(OUT_BESTPHOTO_DIR, f"{ts}_group_bestshot_results.xlsx")

wb = Workbook()
wb.remove(wb.active)

sheet_map = [
    ("Summary", df_summary),
    ("Rename", df_rename),
    ("Ranking", df_combined_rank),
    ("All Evals", df_combined_eval),
]

for name, df in sheet_map:
    ws = wb.create_sheet(title=name)
    write_df_to_worksheet(ws, df)

wb.save(excel_path)
print(f"\nSaved Excel: {excel_path}")

zip_path = os.path.join(OUT_BESTPHOTO_DIR, f"{ts}_ranked_photos_flat.zip")
with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
    for fname in sorted(os.listdir(RANKED_OUTPUT_DIR)):
        full_path = os.path.join(RANKED_OUTPUT_DIR, fname)
        if os.path.isfile(full_path):
            zf.write(full_path, arcname=fname)

print(f"Saved ZIP: {zip_path}")

# files.download(excel_path)
# files.download(zip_path)

print("\nDone.")

"""Run this cell only if you want to save to Google Drive"""

# ==========================================
# CELL 9) Optional: Save Results back to Drive
# ==========================================
DRIVE_OUTPUT_DIR = "/content/drive/MyDrive/LTID/Club/Output/01_Club - small_NoFolderCreation_v5"
os.makedirs(DRIVE_OUTPUT_DIR, exist_ok=True)

if "excel_path" in locals() and os.path.exists(excel_path):
    shutil.copy2(excel_path, os.path.join(DRIVE_OUTPUT_DIR, os.path.basename(excel_path)))
    print(f"Excel saved to Drive: {DRIVE_OUTPUT_DIR}")

# if "zip_path" in locals() and os.path.exists(zip_path):
#     shutil.copy2(zip_path, os.path.join(DRIVE_OUTPUT_DIR, os.path.basename(zip_path)))
#     print(f"ZIP saved to Drive: {DRIVE_OUTPUT_DIR}")

if "RANKED_OUTPUT_DIR" in locals() and os.path.exists(RANKED_OUTPUT_DIR):
    drive_ranked_folder = os.path.join(DRIVE_OUTPUT_DIR, os.path.basename(RANKED_OUTPUT_DIR))
    shutil.copytree(RANKED_OUTPUT_DIR, drive_ranked_folder, dirs_exist_ok=True)
    print("Ranked folder synced to Drive.")





"""## Eye closure"""

# -*- coding: utf-8 -*-
"""
======================================================
  EYE CLOSURE DETECTION v4
  InsightFace (RetinaFace) → GPT-5.4 (judgment)
  Optimized for East Asian faces / group photos
======================================================
"""

# ============================================================
# CELL 1) Install
# ============================================================
!pip -q install insightface onnxruntime opencv-python-headless openai tqdm requests openpyxl Pillow
# !pip -q install "numpy<2.0"   # insightface requires numpy <2

import os, cv2, shutil, zipfile, datetime, requests, json, base64, math
import numpy as np
import pandas as pd
from tqdm import tqdm
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows
from google.colab import drive
from openai import OpenAI
import insightface
from insightface.app import FaceAnalysis

try:
    drive.mount("/content/drive")
except Exception:
    pass

print("InsightFace version:", insightface.__version__)
print("All imports OK ✓")


# ============================================================
# CELL 2) Configuration  ← only section you need to edit
# ============================================================

# ── Paths ────────────────────────────────────────────────────
DRIVE_INPUT_FOLDER = "/content/drive/MyDrive/LTID/Club/01_Club - small"
DRIVE_OUTPUT_DIR   = "/content/drive/MyDrive/LTID/Club/Output/Eye_Closure_v5"

LOCAL_UPLOAD_DIR   = "/content/eye_v4_uploads"
LOCAL_OUTPUT_DIR   = "/content/eye_v4_outputs"

# ── OpenAI ───────────────────────────────────────────────────
from google.colab import userdata
OPENAI_API_KEY = userdata.get('OPENAI_API_KEY')   # or paste key as string
GPT_MODEL      = "gpt-5.4"

# ── InsightFace ───────────────────────────────────────────────
DET_SIZE        = (640, 640)   # detection input size; increase to (1280,1280) for large group shots
DET_THRESH      = 0.35         # lower = catches more faces (inc. small/partial); raise if too many false faces
FACE_PADDING_PCT= 0.25         # % padding added around each detected face bbox before sending to GPT

# ── GPT ──────────────────────────────────────────────────────
GPT_MIN_FACE_PX = 40           # skip GPT if face crop is smaller than this (too blurry to judge)
GPT_RETRY       = 2

# ── Visuals ───────────────────────────────────────────────────
COLOR_CLOSED  = (0,   0, 210)   # BGR deep red
COLOR_OPEN    = (0, 180,  60)   # BGR green
COLOR_NO_FACE = (0, 200, 220)   # BGR yellow (unclear/occluded)
SHOW_OPEN_LABEL = False         # set True to also label open-eye faces (can get noisy)

os.makedirs(LOCAL_UPLOAD_DIR, exist_ok=True)
os.makedirs(LOCAL_OUTPUT_DIR, exist_ok=True)

print("Input :", DRIVE_INPUT_FOLDER)
print("Output:", DRIVE_OUTPUT_DIR)


# ============================================================
# CELL 3) Load images from Drive
# ============================================================
IMAGE_EXTS  = (".png", ".jpg", ".jpeg", ".webp", ".bmp", ".tif", ".tiff")
image_paths = []

if os.path.exists(DRIVE_INPUT_FOLDER):
    for root, _, files in os.walk(DRIVE_INPUT_FOLDER):
        for f in sorted(files):
            if f.lower().endswith(IMAGE_EXTS):
                src = os.path.join(root, f)
                dst = os.path.join(LOCAL_UPLOAD_DIR, f)
                shutil.copy2(src, dst)
                image_paths.append(dst)
    print(f"Loaded {len(image_paths)} images.")
else:
    print(f"ERROR: {DRIVE_INPUT_FOLDER} not found.")


# ============================================================
# CELL 4) Initialize models
# ============================================================

# InsightFace — buffalo_l is the most accurate model pack
# It includes RetinaFace (detection) + 2D106 landmarks
face_app = FaceAnalysis(
    name="buffalo_l",           # downloads ~300 MB on first run, cached after
    allowed_modules=["detection"],  # we only need detection, not recognition
    providers=["CUDAExecutionProvider", "CPUExecutionProvider"],
)
face_app.prepare(ctx_id=0, det_size=DET_SIZE, det_thresh=DET_THRESH)
print("InsightFace (buffalo_l / RetinaFace) ready ✓")

client = OpenAI(api_key=OPENAI_API_KEY)
print("OpenAI client ready ✓")


# ============================================================
# CELL 5) Helper functions
# ============================================================

GPT_PROMPT = """
You are examining a CROPPED IMAGE of a single FACE. Your task is to determine if the eyes are closed.

STEP 1 — has_clear_face: Can you see this person's eye region?
  TRUE  → Eye area is visible (even if eyes are closed, angled, or looking down).
  FALSE → Only back of head / extreme side profile / eyes fully blocked by hair, hands,
          or mask / image too blurry or small to judge.

STEP 2 — eyes_closed: Are the eyes closed?
  TRUE  → The upper eyelid is resting DOWN on or past the lower eyelid. No iris or pupil
          is visible at all. The person is sleeping, blinking, or has eyes shut.
  FALSE → ANY part of the dark iris or pupil is visible, even a small sliver or crescent.

THE MOST COMMON MISTAKE — smiling squint:
  When a person smiles broadly, their cheeks rise and compress the eye opening, making
  eyes look very narrow or almost shut. This is NOT closed eyes.
  Key test: look for the dark iris/pupil. If you can see ANY dark circle or crescent
  behind the eyelid gap → eyes are OPEN (FALSE), regardless of how narrow the gap is.
  The eye shape being narrow or curved/crescent from smiling ≠ closed.

RULES for East Asian faces:
  - Naturally narrow or monolid eyes show only a thin iris line when open → FALSE.
  - Smiling/laughing with crescent-shaped eye openings → still FALSE if iris is visible.
  - Only return TRUE if the eyelid is fully covering the eye with NO iris visible at all.

OTHER CASES:
  - Looking down but pupils visible through eyelid gap → FALSE (open).
  - Glasses do not affect this judgment — look at the eye behind the lens.
  - If has_clear_face is FALSE, set eyes_closed to FALSE.

Return ONLY this JSON (no markdown, no extra text):
{"has_clear_face": true|false, "eyes_closed": true|false, "confidence": "high"|"medium"|"low"}
""".strip()


def pad_bbox(x1, y1, x2, y2, img_w, img_h, pad_pct=FACE_PADDING_PCT):
    """Add percentage-based padding around a face bbox, clamped to image bounds."""
    w, h   = x2 - x1, y2 - y1
    pad_x  = int(w * pad_pct)
    pad_y  = int(h * pad_pct)
    return (
        max(0,     x1 - pad_x),
        max(0,     y1 - pad_y),
        min(img_w, x2 + pad_x),
        min(img_h, y2 + pad_y),
    )


def encode_crop(bgr_crop):
    _, buf = cv2.imencode(".jpg", bgr_crop, [cv2.IMWRITE_JPEG_QUALITY, 93])
    return base64.b64encode(buf).decode("utf-8")


def ask_gpt(face_crop_bgr):
    """
    Send face crop to GPT-5.4.
    Returns (has_clear_face, eyes_closed, confidence).
    """
    h, w = face_crop_bgr.shape[:2]
    if w < GPT_MIN_FACE_PX or h < GPT_MIN_FACE_PX:
        return False, False, "low"

    b64 = encode_crop(face_crop_bgr)

    for attempt in range(GPT_RETRY):
        try:
            resp = client.responses.create(
                model=GPT_MODEL,
                input=[{
                    "role": "user",
                    "content": [
                        {"type": "input_text",  "text": GPT_PROMPT},
                        {"type": "input_image",
                         "image_url": f"data:image/jpeg;base64,{b64}",
                         "detail": "high"},
                    ],
                }],
                reasoning={"effort": "medium"},
            )
            text = resp.output_text.strip()
            # Strip markdown fences if present
            if "```" in text:
                text = text.split("```")[1]
                if text.startswith("json"): text = text[4:]
            data = json.loads(text.strip())
            return (
                bool(data.get("has_clear_face", False)),
                bool(data.get("eyes_closed",    False)),
                str(data.get("confidence",      "medium")),
            )
        except Exception as e:
            if attempt == GPT_RETRY - 1:
                print(f"    GPT error: {e}")
    return False, False, "low"


def draw_corner_box(img, x1, y1, x2, y2, color, thickness):
    """Draw rectangle with corner accent marks."""
    cv2.rectangle(img, (x1, y1), (x2, y2), color, thickness)
    cl = max(8, (x2 - x1) // 8)
    for cx, cy, dx, dy in [(x1,y1,1,1),(x2,y1,-1,1),(x1,y2,1,-1),(x2,y2,-1,-1)]:
        cv2.line(img, (cx,cy), (cx+dx*cl, cy),      color, thickness+1)
        cv2.line(img, (cx,cy), (cx, cy+dy*cl),      color, thickness+1)


def draw_label(img, text, x1, y1, color):
    font, scale, thick = cv2.FONT_HERSHEY_DUPLEX, 0.55, 1
    (tw, th), _ = cv2.getTextSize(text, font, scale, thick)
    pad = 4
    label_y = y1 - th - pad*2 if y1 - th - pad*2 > 0 else y1 + th + pad*2 + 2
    cv2.rectangle(img, (x1, label_y-th-pad), (x1+tw+pad*2, label_y+pad), color, -1)
    cv2.putText(img, text, (x1+pad, label_y), font, scale, (255,255,255), thick, cv2.LINE_AA)


# ============================================================
# CELL 6) Main processing loop
# ============================================================

ts         = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
MARKED_DIR = os.path.join(LOCAL_OUTPUT_DIR, f"{ts}_marked")
CLEAN_DIR  = os.path.join(LOCAL_OUTPUT_DIR, f"{ts}_clean")
os.makedirs(MARKED_DIR, exist_ok=True)
os.makedirs(CLEAN_DIR,  exist_ok=True)

all_results   = []
all_face_rows = []

for img_path in tqdm(image_paths, desc="Processing"):
    fname     = os.path.basename(img_path)
    stem, _   = os.path.splitext(fname)

    bgr = cv2.imread(img_path)
    if bgr is None:
        print(f"  SKIP (load failed): {fname}")
        all_results.append({"file_name": fname, "status": "load_error"})
        continue

    img_h, img_w = bgr.shape[:2]
    annotated    = bgr.copy()
    thickness    = max(2, img_h // 400)

    # ── Step 1: InsightFace face detection ───────────────────
    # InsightFace expects RGB
    rgb   = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
    faces = face_app.get(rgb)   # list of Face objects

    clear_faces      = 0
    closed_eye_faces = 0

    for f_idx, face in enumerate(faces):
        # face.bbox → [x1, y1, x2, y2] float
        x1, y1, x2, y2 = map(int, face.bbox)
        x1, y1 = max(0, x1), max(0, y1)
        x2, y2 = min(img_w, x2), min(img_h, y2)

        # Padded face crop for GPT
        px1, py1, px2, py2 = pad_bbox(x1, y1, x2, y2, img_w, img_h)
        face_crop = bgr[py1:py2, px1:px2]

        if face_crop.size == 0:
            continue

        # ── Step 2: GPT judgment ─────────────────────────────
        has_clear_face, eyes_closed, confidence = ask_gpt(face_crop)

        all_face_rows.append({
            "file_name"     : fname,
            "face_index"    : f_idx + 1,
            "det_score"     : round(float(face.det_score), 3),
            "has_clear_face": has_clear_face,
            "eyes_closed"   : eyes_closed,
            "confidence"    : confidence,
            "bbox"          : f"{x1},{y1},{x2},{y2}",
        })

        # ── Step 3: Draw annotation ───────────────────────────
        if has_clear_face:
            clear_faces += 1
            if eyes_closed:
                closed_eye_faces += 1
                draw_corner_box(annotated, x1, y1, x2, y2, COLOR_CLOSED, thickness)
                draw_label(annotated, f"EYES CLOSED [{confidence[0].upper()}]", x1, y1, COLOR_CLOSED)
            else:
                draw_corner_box(annotated, x1, y1, x2, y2, COLOR_OPEN, thickness)
                if SHOW_OPEN_LABEL:
                    draw_label(annotated, "OPEN", x1, y1, COLOR_OPEN)
        else:
            # Thin yellow box — face detected but occluded/unclear
            draw_corner_box(annotated, x1, y1, x2, y2, COLOR_NO_FACE, max(1, thickness//2))

    # ── Step 4: Counter overlay ───────────────────────────────
    font_scale = max(0.6, img_h / 700)
    ot  = max(2, thickness)
    oy  = int(0.06 * img_h)
    gap = int(oy * 0.75)

    overlay_lines = [
        (f"People Detected : {len(faces)}",      (200, 200, 200)),
        (f"Clear Faces     : {clear_faces}",      COLOR_OPEN),
        (f"Eyes Closed     : {closed_eye_faces}", COLOR_CLOSED),
    ]
    for i, (text, color) in enumerate(overlay_lines):
        cv2.putText(annotated, text,
                    (int(0.02*img_w), oy + i * gap),
                    cv2.FONT_HERSHEY_SIMPLEX, font_scale, color, ot)

    # ── Step 5: Save ──────────────────────────────────────────
    cv2.imwrite(os.path.join(MARKED_DIR, f"{stem}_marked.jpg"), annotated, [cv2.IMWRITE_JPEG_QUALITY, 95])
    cv2.imwrite(os.path.join(CLEAN_DIR,  f"{stem}_clean.jpg"),  bgr,       [cv2.IMWRITE_JPEG_QUALITY, 95])

    all_results.append({
        "file_name"       : fname,
        "status"          : "ok",
        "faces_detected"  : len(faces),
        "clear_faces"     : clear_faces,
        "closed_eye_faces": closed_eye_faces,
        "has_closed_eyes" : closed_eye_faces > 0,
    })

    closed_flag = "⚠" if closed_eye_faces > 0 else "✓"
    print(f"  {closed_flag}  {fname}  →  people: {len(faces)}  |  clear faces: {clear_faces}  |  eyes closed: {closed_eye_faces}")

print(f"\n✓ Done. Marked → {MARKED_DIR}")


# ============================================================
# CELL 7) Excel report + ZIPs + Drive sync
# ============================================================

df_summary   = pd.DataFrame(all_results)
df_face_rows = pd.DataFrame(all_face_rows)

total        = len(df_summary)
total_people = int(df_summary["faces_detected"].sum()) if "faces_detected" in df_summary else 0
with_closed  = int(df_summary["has_closed_eyes"].sum()) if "has_closed_eyes" in df_summary else 0
total_closed = int(df_summary["closed_eye_faces"].sum()) if "closed_eye_faces" in df_summary else 0

print(f"\n{'='*55}\n  EYE CLOSURE DETECTION v4 — SUMMARY")
print(f"  Total images    : {total}")
print(f"  Total people    : {total_people}")
print(f"  With closed eyes: {with_closed}  ({with_closed/max(total,1)*100:.1f}%)")
print(f"  Closed-eye faces: {total_closed}\n{'='*55}")


def _write_sheet(wb, title, df):
    ws = wb.create_sheet(title=title)
    if df is None or df.empty:
        ws.append(["No data"]); return
    df2 = df.copy()
    for col in df2.columns:
        df2[col] = df2[col].apply(
            lambda x: "" if pd.isna(x) else str(x) if isinstance(x, (list,dict,set)) else x)
    for row in dataframe_to_rows(df2, index=False, header=True):
        ws.append(row)
    for cc in ws.columns:
        ws.column_dimensions[cc[0].column_letter].width = min(
            max(len(str(c.value or "")) for c in cc) + 2, 45)


wb = Workbook(); wb.remove(wb.active)
_write_sheet(wb, "Summary",     df_summary)
_write_sheet(wb, "Face Detail", df_face_rows)

excel_path = os.path.join(LOCAL_OUTPUT_DIR, f"{ts}_eye_closure_report.xlsx")
wb.save(excel_path)
print(f"Excel → {excel_path}")

# for folder, label in [(MARKED_DIR, "marked"), (CLEAN_DIR, "clean")]:
#     zp = os.path.join(LOCAL_OUTPUT_DIR, f"{ts}_{label}_photos.zip")
#     with zipfile.ZipFile(zp, "w", zipfile.ZIP_DEFLATED) as zf:
#         for f in sorted(os.listdir(folder)):
#             fp = os.path.join(folder, f)
#             if os.path.isfile(fp): zf.write(fp, arcname=f)
#     print(f"{label.capitalize()} ZIP → {zp}")

os.makedirs(DRIVE_OUTPUT_DIR, exist_ok=True)
for f in os.listdir(LOCAL_OUTPUT_DIR):
    fp = os.path.join(LOCAL_OUTPUT_DIR, f)
    if os.path.isfile(fp):
        shutil.copy2(fp, os.path.join(DRIVE_OUTPUT_DIR, f))
for folder in [MARKED_DIR, CLEAN_DIR]:
    dst = os.path.join(DRIVE_OUTPUT_DIR, os.path.basename(folder))
    shutil.copytree(folder, dst, dirs_exist_ok=True)
    print(f"Synced {os.path.basename(folder)} → Drive")

print("\n✅ Complete.")

