# -*- coding: utf-8 -*-
"""protagonist_eyes_closed_&_japanese_20/4_Snap_Picture.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JEi-RjLCMBYGzNZLicT5H97NFP4HJ7pI
"""

# ================================
# CELL 1) Install + Imports
# ================================
# !pip -q install -U google-genai tqdm openpyxl

import os
import io
import re
import json
import base64
import shutil
import zipfile
import datetime
from typing import List, Dict, Any, Optional

import pandas as pd
import numpy as np
from PIL import Image, ExifTags
from tqdm import tqdm

# Using the new google-genai SDK
from google import genai
from google.genai import types
from google.colab import files, drive
from IPython.display import display
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows

import time
from google.colab import userdata


print("OK - All imports successful")

# --- API Configuration ---
# Gemini
try:
    GEMINI_API_KEY = userdata.get("GOOGLE_API_KEY")
except Exception:
    GEMINI_API_KEY = "YOUR_GEMINI_KEY"

client = genai.Client(api_key=GEMINI_API_KEY)

# OpenAI
try:
    OPENAI_API_KEY = userdata.get("OPENAI_API_KEY")
    from openai import OpenAI
    oa_client = OpenAI(api_key=OPENAI_API_KEY)
except Exception:
    OPENAI_API_KEY = None
    oa_client = None

# Model Selection: Change this to 'gpt-4o' or similar to use OpenAI
MODEL_NAME = "gpt-5.4"

# Directory Configuration
UPLOAD_DIR = "/content/snap_photo_uploads"
OUTPUT_DIR = "/content/snap_photo_outputs"
os.makedirs(UPLOAD_DIR, exist_ok=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)

print(f"Model: {MODEL_NAME}")
print(f"OpenAI Client Initialized: {oa_client is not None}")

# =========================
# CELL ) Load Images from Google Drive
# =========================

drive.mount("/content/drive")

DRIVE_SOURCE_FOLDER = "/content/drive/MyDrive/LTID/Photography_Pipeline/Snap Pictures Samples/Best shot folders/"

if os.path.exists(DRIVE_SOURCE_FOLDER):
    exts = (".png", ".jpg", ".jpeg", ".webp", ".bmp", ".tif", ".tiff")
    found_count = 0
    folder_map = {}
    for root, dirs, filenames in os.walk(DRIVE_SOURCE_FOLDER):
        rel_folder = os.path.relpath(root, DRIVE_SOURCE_FOLDER)
        if rel_folder == ".":
            rel_folder = "root"
        for f in filenames:
            if f.lower().endswith(exts):
                src = os.path.join(root, f)
                unique_name = f"{rel_folder.replace(os.sep, '_')}_{f}" if rel_folder != "root" else f
                dst = os.path.join(UPLOAD_DIR, unique_name)
                shutil.copy2(src, dst)
                folder_map[dst] = rel_folder
                found_count += 1
    image_paths = sorted([os.path.join(UPLOAD_DIR, f) for f in os.listdir(UPLOAD_DIR) if f.lower().endswith(exts)])
    print(f"Successfully loaded {found_count} images from Drive.")
    print(f"Total images: {len(image_paths)}")
    folder_counts = {}
    for path, folder in folder_map.items():
        folder_counts[folder] = folder_counts.get(folder, 0) + 1
    print(f"\nImages by folder:")
    for folder, count in sorted(folder_counts.items()):
        print(f"  {folder}: {count} images")
else:
    print(f"Error: Source folder {DRIVE_SOURCE_FOLDER} not found.")
    image_paths = []
    folder_map = {}

"""**Alternative: Run this cell if you want to upload images manually instead of using Google Drive**"""

# =========================
# CELL 4b) Alternative: Manual Upload
# =========================
# Skip this cell if you already loaded from Google Drive

def upload_images_to_folder(dst_dir: str) -> tuple:
    os.makedirs(dst_dir, exist_ok=True)
    uploaded = files.upload()
    folder_map = {}
    for fn in uploaded.keys():
        src = f"/content/{fn}"
        if fn.lower().endswith(".zip"):
            with zipfile.ZipFile(src, "r") as z:
                z.extractall(dst_dir)
            os.remove(src)
        else:
            shutil.move(src, os.path.join(dst_dir, fn))
    exts = (".png", ".jpg", ".jpeg", ".webp", ".bmp", ".tif", ".tiff")
    image_paths = []
    for root, _, files_ in os.walk(dst_dir):
        rel_folder = os.path.relpath(root, dst_dir)
        if rel_folder == ".":
            rel_folder = "root"
        for f in files_:
            if f.lower().endswith(exts):
                full_path = os.path.join(root, f)
                image_paths.append(full_path)
                folder_map[full_path] = rel_folder
    image_paths = sorted(image_paths)
    print(f"Uploaded images found: {len(image_paths)}")
    return image_paths, folder_map

# Uncomment to use manual upload:
# image_paths, folder_map = upload_images_to_folder(UPLOAD_DIR)

# Selection Configuration
BEST_TOKEN = "本"

# Scoring Weights
WEIGHT_TECHNICAL = 0.30
WEIGHT_EXPRESSION = 0.25
WEIGHT_COMPOSITION = 0.25
WEIGHT_RARITY = 0.20

# Event-aware configuration
EVENT_TYPE = "general"
TARGET_GRADE = None
MIN_FINAL_PHOTOS = 20
MAX_FINAL_PHOTOS = 25
MAX_REPEAT_SAME_PERSON = 2

EVENT_RULES = {
    "general": {
        "required_tag_groups": [],
        "must_have_landmark": 0,
        "cheering_range": (0, 0),
        "max_transit_or_meal": None,
        "balance_by_class": False,
        "balance_by_day": False,
        "require_ball_visible": False,
    },
    "entrance_ceremony": {
        "required_tag_groups": [
            ["entrance sign", "memorial"],
            ["full group", "group shot"],
            ["procession", "entrance procession"],
            ["principal speech"],
            ["student representative speech", "representative speech"],
            ["homeroom teacher introduction", "teacher introduction"],
        ],
        "must_have_landmark": 0,
        "cheering_range": (0, 0),
        "max_transit_or_meal": None,
        "balance_by_class": False,
        "balance_by_day": False,
        "require_ball_visible": False,
    },
    "field_trip": {
        "required_tag_groups": [["landmark", "destination"]],
        "must_have_landmark": 2,
        "cheering_range": (0, 0),
        "max_transit_or_meal": 2,
        "balance_by_class": False,
        "balance_by_day": False,
        "require_ball_visible": False,
    },
    "sports_festival": {
        "required_tag_groups": [["athlete oath"], ["award ceremony", "results announcement"]],
        "must_have_landmark": 0,
        "cheering_range": (1, 2),
        "max_transit_or_meal": None,
        "balance_by_class": True,
        "balance_by_day": False,
        "require_ball_visible": False,
    },
    "other_athletic": {
        "required_tag_groups": [["start"], ["finish"]],
        "must_have_landmark": 0,
        "cheering_range": (0, 1),
        "max_transit_or_meal": None,
        "balance_by_class": False,
        "balance_by_day": False,
        "require_ball_visible": True,
    },
    "cultural_festival": {
        "required_tag_groups": [["stage performance"], ["class exhibit", "entrance gate", "club activity"]],
        "must_have_landmark": 0,
        "cheering_range": (0, 0),
        "max_transit_or_meal": None,
        "balance_by_class": True,
        "balance_by_day": False,
        "require_ball_visible": False,
    },
    "other_cultural": {
        "required_tag_groups": [["award ceremony"], ["group shot"]],
        "must_have_landmark": 0,
        "cheering_range": (0, 0),
        "max_transit_or_meal": None,
        "balance_by_class": True,
        "balance_by_day": False,
        "require_ball_visible": False,
    },
    "school_trip": {
        "required_tag_groups": [["landmark", "destination"]],
        "must_have_landmark": 2,
        "cheering_range": (0, 0),
        "max_transit_or_meal": 2,
        "balance_by_class": False,
        "balance_by_day": True,
        "require_ball_visible": False,
    },
    "other_off_campus": {
        "required_tag_groups": [["landmark", "destination"]],
        "must_have_landmark": 1,
        "cheering_range": (0, 0),
        "max_transit_or_meal": 2,
        "balance_by_class": False,
        "balance_by_day": True,
        "require_ball_visible": False,
    },
}

EVENT_NAME_HINTS = {
    "entrance_ceremony": [
        "entrance_ceremony", "school_entrance", "entrance ceremony", "入学式", "school entrance",
    ],
    "field_trip": [
        "field_trip", "field trip", "遠足",
    ],
    "sports_festival": [
        "sports_festival", "sport_event", "sports event", "体育祭", "athletic_meet",
    ],
    "other_athletic": [
        "marathon", "ball game", "ball_game", "relay", "athletic",
    ],
    "cultural_festival": [
        "cultural_festival", "cultural festival", "文化祭",
    ],
    "other_cultural": [
        "choir", "speech_contest", "speech contest", "合唱", "弁論",
    ],
    "school_trip": [
        "school_trip", "school trip", "修学旅行",
    ],
    "other_off_campus": [
        "forest school", "british hills", "off_campus", "校外",
    ],
}

# =========================
# CELL 3) Helper Functions  ← REPLACE YOUR EXISTING CELL 3 WITH THIS ENTIRE BLOCK
# =========================

def get_file_date_string(path: str) -> str:
    try:
        img = Image.open(path)
        exif = img._getexif()
        if exif:
            for tag_id, value in exif.items():
                tag = ExifTags.TAGS.get(tag_id, tag_id)
                if tag == "DateTimeOriginal" and value:
                    return str(value)[:10].replace(":", "")
    except Exception:
        pass
    try:
        mod_time = os.path.getmtime(path)
        return datetime.datetime.fromtimestamp(mod_time).strftime("%Y%m%d")
    except Exception:
        return "00000000"


def load_image_for_gemini(path: str) -> Image.Image:
    img = Image.open(path)
    if img.mode != "RGB":
        img = img.convert("RGB")
    return img


def parse_json_response(text: str) -> dict:
    if not text:
        raise ValueError("Empty model response")
    import re
    match = re.search(r'\{.*\}', text, re.DOTALL)
    if not match:
        raise ValueError(f"Could not find JSON object in response: {text}")
    json_str = match.group(0)
    try:
        return json.loads(json_str)
    except json.JSONDecodeError:
        cleaned = re.sub(r'\n', ' ', json_str)
        return json.loads(cleaned)


def unique_path(path: str) -> str:
    if not os.path.exists(path):
        return path
    base, ext = os.path.splitext(path)
    k = 2
    while True:
        candidate = f"{base}__dup{k}{ext}"
        if not os.path.exists(candidate):
            return candidate
        k += 1


def coerce_bool(value: Any, default: bool = False) -> bool:
    if isinstance(value, bool):
        return value
    if value is None:
        return default
    s = str(value).strip().lower()
    if s in {"true", "1", "yes", "y"}:
        return True
    if s in {"false", "0", "no", "n"}:
        return False
    return default


def normalize_event_type(event_type: Optional[str]) -> str:
    if not event_type:
        return "general"
    key = str(event_type).strip().lower().replace("-", "_").replace(" ", "_")
    aliases = {
        "entrance": "entrance_ceremony",
        "entrance_ceremony": "entrance_ceremony",
        "field_trip": "field_trip",
        "sports": "sports_festival",
        "sports_festival": "sports_festival",
        "athletic": "other_athletic",
        "other_athletic": "other_athletic",
        "cultural": "cultural_festival",
        "cultural_festival": "cultural_festival",
        "other_cultural": "other_cultural",
        "school_trip": "school_trip",
        "off_campus": "other_off_campus",
        "other_off_campus": "other_off_campus",
        "general": "general",
    }
    return aliases.get(key, "general")


def infer_event_type_from_folder(folder_name: Optional[str]) -> str:
    if not folder_name:
        return normalize_event_type(EVENT_TYPE)
    raw = str(folder_name).strip().lower().replace("-", "_")
    for event_key, hints in EVENT_NAME_HINTS.items():
        for hint in hints:
            hint_norm = str(hint).lower().replace("-", "_")
            if hint_norm in raw:
                return event_key
    return normalize_event_type(EVENT_TYPE)


def get_event_rules(event_type: Optional[str]) -> Dict[str, Any]:
    return EVENT_RULES.get(normalize_event_type(event_type), EVENT_RULES["general"])


def normalize_tags(value: Any) -> List[str]:
    if value is None:
        return []
    if isinstance(value, list):
        tags = value
    elif isinstance(value, str):
        tags = re.split(r"[,;|]", value)
    else:
        tags = [str(value)]
    return [str(t).strip().lower() for t in tags if str(t).strip()]


def normalize_class_hint(value: Any) -> str:
    if value is None:
        return "unknown"
    text = str(value).strip().lower()
    if not text or text == "unknown":
        return "unknown"
    class_ids = []
    for match in re.finditer(r"(?:class|grade|組)?\s*(\d{1,2})\s*(?:組|gumi|class|grade)?", text):
        class_ids.append(match.group(1))
    if not class_ids:
        class_ids = re.findall(r"\d{1,2}", text)
    unique_ids = []
    for class_id in class_ids:
        if class_id not in unique_ids:
            unique_ids.append(class_id)
    if unique_ids:
        return "class_" + "_".join(unique_ids)
    cleaned = re.sub(r"[^a-z0-9]+", "_", text).strip("_")
    return cleaned or "unknown"


def build_photo_eval_prompt(event_type: str, target_grade: Optional[str], folder_name: str) -> str:
    normalized_event = normalize_event_type(event_type)
    rules = get_event_rules(normalized_event)

    event_guidance = {
        "general": "Use general school-event best-shot criteria.",
        "entrance_ceremony": (
            "Include key ceremony moments: memorial photo in front of the entrance sign, full group shot, "
            "entrance procession, principal's speech, student representative's speech, and homeroom teacher introduction. "
            "Ensure balanced coverage across these scenes."
        ),
        "field_trip": (
            "Prefer photos that clearly show landmarks so the destination is identifiable. "
            "Avoid relying only on camera-facing group photos. "
            "Ensure a mix of contextual landmark and activity-based shots."
        ),
        "sports_festival": (
            "Use photos from all classes as evenly as possible. "
            "Cover all events for the target grade when possible. "
            "Include 1–2 cheering shots if available. "
            "Include athlete's oath, results announcement, and award ceremony if the target grade is involved. "
            "Ensure balanced representation across classes and event types."
        ),
        "other_athletic": (
            "Apply sports festival selection logic. "
            "For ball game tournaments, prioritize shots where the ball is clearly visible. "
            "For marathons, include start and finish scenes if available. "
            "Class identification may not be possible, so equal class representation is not required."
        ),
        "cultural_festival": (
            "Use photos from all classes as evenly as possible. "
            "Ensure balanced coverage of stage performances across grade levels. "
            "When class-specific photos are limited, include entrance gate, club activities, or exhibition photos."
        ),
        "other_cultural": (
            "Apply cultural festival selection logic. "
            "For choir festivals, include one singing photo per class and include award ceremonies if available. "
            "For speech contests, include one photo per presenter, along with award ceremonies and group shots if available."
        ),
        "school_trip": (
            "Include landmarks so the destination is identifiable. "
            "Distribute photos evenly across all itinerary days. "
            "Limit transit (e.g., train, plane) and meal photos to approximately 1–2 images. "
            "Ensure a balanced mix of locations and activities."
        ),
        "other_off_campus": (
            "Apply field trip and school trip criteria. "
            "Ensure landmarks or location context are visible and distribute photos across activities or days when applicable."
        ),
    }

    target_grade_text = (
        f"Target grade year is '{target_grade}'. Prioritize this grade by visual cues such as stamp, jersey color, class shirt, bib number, and context."
        if target_grade else
        "Target grade is not explicitly provided. Infer likely target-grade relevance carefully."
    )

    required_groups = rules.get("required_tag_groups", [])
    required_as_text = "; ".join([" / ".join(group) for group in required_groups]) if required_groups else "none"

    return f"""
あなたはプロの学校卒業アルバム写真選定者です。画像を分析し、JSONのみを返してください。
すべての文字列フィールド（ng_reason、short_commentなど）は必ず日本語で回答してください。

コンテキスト:
- イベント種別: {normalized_event}
- ソースフォルダ: {folder_name}
- {target_grade_text}
- イベントガイダンス: {event_guidance.get(normalized_event, event_guidance['general'])}
- 必須シーンカテゴリ: {required_as_text}

タスク1: NGフィルター（以下のいずれかに該当する場合のみ is_ng=true）
- 他学年の生徒が大多数を占めている（少数は許容）
- 主役被写体のピントがずれている、またはブレがある
- 主役のフード（口の中の食べ物）が見えている
- 主役の不適切なジェスチャー（中指、わいせつなポーズ）
- 下着の露出など不適切な露出
- 主役の顔が切れている、または完全に隠れている
- 主役の顔の詳細が失われるほどの極端な露出オーバー

★ 目閉じ・失敗瞬間のNG判定ルール（重要）:
  まず写真の「主役」を特定してください（中央に配置、ピントが合っている、
  カメラを向いている、または文脈上シーンの焦点となっている人物）。
  - 主役が目を完全に閉じている、または明らかに不格好な失敗の瞬間 → is_ng=true
  - 背景や周囲の人物のみが目を閉じている/失敗の瞬間であり、
    主役は問題ない → is_ng=false のまま。
    protagonist_eyes_closed=false、bystander_issue=true とし、
    expression_score を1点減点する。
  - 笑いによる目の細め、逆光による squint など曖昧なケース →
    is_ng=false のまま、expression_score を1点減点する。

※ 以下はNGではないが、スコアリングとタグ付けに反映すること:
- 連写・バースト写真が多い → rarity_score を下げる
- 同一人物が頻繁に登場 → rarity_score を下げる
- 特定クラスが過剰代表 → event_relevance を下げる
- 類似ポーズ・アングルの繰り返し → rarity_score を下げる

タスク2: スコアリング（0〜10の整数）
- technical_score: ピント・露出・色・鮮明さ
- expression_score: 自然な表情・感情的な質（周囲の目閉じがある場合は若干減点）
- composition_score: フレーミング・奥行き・シーンの読みやすさ
- rarity_score: 独自性・多様性への貢献（重複・連写・ポーズ繰り返しは減点）
- target_grade_relevance: 対象学年がどの程度写っているか
- event_relevance: 行事の全体カバレッジと多様性にどれだけ貢献するか

タスク3: 最終レイアウト用タグ付け
- shot_type_tags: 「ランドマーク」「集合写真」「スピーチ」「行進」「応援」「表彰式」
  「スタート」「ゴール」「ステージ発表」「移動中」「食事」「ボール見える」
  「連写」「類似構図」「被写体重複」などの簡潔なタグ（日本語で記述）
- class_hint: クラス・組の推定（不明な場合は "不明"）
- day_hint: 日程・行程の推定（不明な場合は "不明"）
- person_signature: 繰り返し登場する主要被写体の識別子（不明な場合は "不明"）

出力形式（厳密なJSONのみ）:
{{
  "is_ng": true または false,
  "ng_reason": "文字列 または null",
  "technical_score": 整数,
  "expression_score": 整数,
  "composition_score": 整数,
  "rarity_score": 整数,
  "target_grade_relevance": 整数,
  "event_relevance": 整数,
  "blur_detected": true または false,
  "exposure_issue": "なし" または "露出不足" または "露出過多" または "逆光",
  "protagonist_eyes_closed": true または false,
  "protagonist_imperfect_moment": true または false,
  "bystander_issue": true または false,
  "eyes_closed": true または false,
  "face_visible": true または false,
  "landmark_visible": true または false,
  "ball_visible": true または false,
  "cheering_shot": true または false,
  "shot_type_tags": ["タグ1", "タグ2"],
  "class_hint": "文字列",
  "day_hint": "文字列",
  "person_signature": "文字列",
  "short_comment": "一文で（日本語）"
}}
""".strip()

print("Helper functions updated: protagonist-aware NG logic + Japanese prompt output.")

# =========================
# CELL 5) Updated Strict NG Filter + Photo Scoring Prompt
# =========================

PHOTO_EVAL_PROMPT = build_photo_eval_prompt(EVENT_TYPE, TARGET_GRADE, "root")
print("Prompt updated with event-aware criteria and spread tags.")

def evaluate_photo(
    image_path: str,
    folder_name: str = "unknown",
    event_type: str = EVENT_TYPE,
    target_grade: Optional[str] = TARGET_GRADE,
    model_name: str = MODEL_NAME,
) -> dict:
    try:
        prompt = build_photo_eval_prompt(event_type, target_grade, folder_name)

        if "gpt" in model_name.lower():
            if not oa_client:
                raise ValueError("OpenAI client not initialized. Check API Key.")

            with open(image_path, "rb") as f:
                base64_image = base64.b64encode(f.read()).decode('utf-8')

            response = oa_client.chat.completions.create(
                model=model_name,
                messages=[
                    {
                        "role": "user",
                        "content": [
                            {"type": "text", "text": prompt},
                            {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{base64_image}"}}
                        ],
                    }
                ],
                response_format={"type": "json_object"}
            )
            result = json.loads(response.choices[0].message.content)

        else:
            img = load_image_for_gemini(image_path)
            response = client.models.generate_content(
                model=model_name,
                contents=[prompt, img],
                config=types.GenerateContentConfig(
                    temperature=0.1,
                    max_output_tokens=2048,
                    response_mime_type="application/json"
                )
            )
            result = parse_json_response(response.text)

        # ── Defaults ──────────────────────────────────────────────────────────
        defaults = {
            "is_ng": False,
            "ng_reason": None,
            "technical_score": 5,
            "expression_score": 5,
            "composition_score": 5,
            "rarity_score": 5,
            "blur_detected": False,
            "exposure_issue": "なし",
            "eyes_closed": False,
            # NEW protagonist-aware fields
            "protagonist_eyes_closed": False,
            "protagonist_imperfect_moment": False,
            "bystander_issue": False,
            "face_visible": True,
            "short_comment": "",
            "target_grade_relevance": 5,
            "event_relevance": 5,
            "landmark_visible": False,
            "ball_visible": False,
            "cheering_shot": False,
            "shot_type_tags": [],
            "class_hint": "不明",
            "day_hint": "不明",
            "person_signature": "不明",
        }

        for k, v in defaults.items():
            result.setdefault(k, v)

        # ── Normalise booleans ─────────────────────────────────────────────────
        result["is_ng"]                        = coerce_bool(result.get("is_ng"), False)
        result["blur_detected"]                = coerce_bool(result.get("blur_detected"), False)
        result["face_visible"]                 = coerce_bool(result.get("face_visible"), True)
        result["landmark_visible"]             = coerce_bool(result.get("landmark_visible"), False)
        result["ball_visible"]                 = coerce_bool(result.get("ball_visible"), False)
        result["cheering_shot"]                = coerce_bool(result.get("cheering_shot"), False)
        result["protagonist_eyes_closed"]      = coerce_bool(result.get("protagonist_eyes_closed"), False)
        result["protagonist_imperfect_moment"] = coerce_bool(result.get("protagonist_imperfect_moment"), False)
        result["bystander_issue"]              = coerce_bool(result.get("bystander_issue"), False)

        # Keep legacy eyes_closed field derived from protagonist field
        # so any downstream code that still reads eyes_closed works correctly
        result["eyes_closed"] = result["protagonist_eyes_closed"]

        # ── Normalise tags ─────────────────────────────────────────────────────
        result["shot_type_tags"] = normalize_tags(result.get("shot_type_tags", []))

        # ── Balance-aware signals ──────────────────────────────────────────────
        tags = set(result["shot_type_tags"])
        result["has_burst"]               = any("連写" in t or "burst" in t for t in tags)
        result["has_similar_composition"] = any(("類似" in t and "構図" in t) or ("similar" in t and "composition" in t) for t in tags)
        result["has_duplicate_subject"]   = any("被写体重複" in t or "duplicate" in t for t in tags)

        # ── Protagonist-aware NG override ──────────────────────────────────────
        # If the model set is_ng=True citing eyes/imperfect but the protagonist
        # is actually fine, demote to a score penalty rather than a hard NG.
        if result.get("is_ng") and result.get("ng_reason"):
            reason_lower = str(result["ng_reason"]).lower()
            eyes_keywords = (
                "eye", "closed", "blink", "imperfect", "awkward",
                "目閉", "まばたき", "失敗", "不格好", "目をつぶ",
            )
            if any(kw in reason_lower for kw in eyes_keywords):
                if not result["protagonist_eyes_closed"] and not result["protagonist_imperfect_moment"]:
                    # Bystander issue only — remove NG, apply expression penalty
                    result["is_ng"]           = False
                    result["ng_reason"]       = None
                    result["bystander_issue"] = True
                    result["expression_score"] = max(0, int(result.get("expression_score", 5)) - 1)

        return result

    except Exception as e:
        print(f"Error processing {os.path.basename(image_path)}: {e}")
        return {"is_ng": True, "ng_reason": f"評価エラー: {str(e)}"}

print("Evaluation function updated: protagonist-aware NG + Japanese defaults.")

# =========================
# CELL 7) Process All Photos with Rate Limiting
# =========================

def process_all_photos(image_paths: List[str], folder_map: Dict[str, str]) -> pd.DataFrame:
    all_results = []

    for img_path in tqdm(image_paths, desc="Evaluating photos"):
        folder = folder_map.get(img_path, "unknown")

        eval_result = evaluate_photo(
            image_path=img_path,
            folder_name=folder,
            event_type=infer_event_type_from_folder(folder),
            target_grade=TARGET_GRADE,
        )

        result = {
            "file_name":                    os.path.basename(img_path),
            "path":                         img_path,
            "folder":                       folder,
            "event_type":                   infer_event_type_from_folder(folder),
            "is_ng":                        bool(eval_result.get("is_ng", False)),
            "ng_reason":                    eval_result.get("ng_reason"),
            "technical_score":              eval_result.get("technical_score", 0),
            "expression_score":             eval_result.get("expression_score", 0),
            "composition_score":            eval_result.get("composition_score", 0),
            "rarity_score":                 eval_result.get("rarity_score", 0),
            "blur_detected":                eval_result.get("blur_detected", False),
            "exposure_issue":               eval_result.get("exposure_issue", "なし"),
            "eyes_closed":                  eval_result.get("eyes_closed", False),
            # NEW protagonist-aware fields
            "protagonist_eyes_closed":      eval_result.get("protagonist_eyes_closed", False),
            "protagonist_imperfect_moment": eval_result.get("protagonist_imperfect_moment", False),
            "bystander_issue":              eval_result.get("bystander_issue", False),
            "face_visible":                 eval_result.get("face_visible", True),
            "short_comment":                eval_result.get("short_comment", ""),
            "target_grade_relevance":       eval_result.get("target_grade_relevance", 5),
            "event_relevance":              eval_result.get("event_relevance", 5),
            "landmark_visible":             eval_result.get("landmark_visible", False),
            "ball_visible":                 eval_result.get("ball_visible", False),
            "cheering_shot":                eval_result.get("cheering_shot", False),
            "shot_type_tags":               eval_result.get("shot_type_tags", []),
            "class_hint":                   eval_result.get("class_hint", "不明"),
            "day_hint":                     eval_result.get("day_hint", "不明"),
            "person_signature":             eval_result.get("person_signature", "不明"),
            "has_burst":                    eval_result.get("has_burst", False),
            "has_similar_composition":      eval_result.get("has_similar_composition", False),
            "has_duplicate_subject":        eval_result.get("has_duplicate_subject", False),
        }

        all_results.append(result)
        time.sleep(5)

    df = pd.DataFrame(all_results)

    # Redundancy penalty
    df["redundancy_penalty"] = (
        df["has_burst"].astype(int) * 0.15 +
        df["has_similar_composition"].astype(int) * 0.10 +
        df["has_duplicate_subject"].astype(int) * 0.20
    )

    df["quality_score"] = (
        df["technical_score"] * WEIGHT_TECHNICAL +
        df["expression_score"] * WEIGHT_EXPRESSION +
        df["composition_score"] * WEIGHT_COMPOSITION +
        df["rarity_score"] * WEIGHT_RARITY
    )

    df["total_score"] = (
        df["quality_score"] * 0.80 +
        df["event_relevance"] * 0.15 +
        df["target_grade_relevance"] * 0.05
    )

    df["total_score"] = df["total_score"] * (1 - df["redundancy_penalty"])
    df.loc[df["is_ng"] == True, "total_score"] = 0

    return df

df_results = process_all_photos(image_paths, folder_map)

# =========================
# CELL 9) Select Best Photos (Criteria-Based)  ← REPLACE YOUR EXISTING CELL 9 WITH THIS ENTIRE BLOCK
# =========================

def select_best_by_threshold(df: pd.DataFrame) -> pd.DataFrame:

    def row_has_any_tag(tags: List[str], terms: List[str]) -> bool:
        return any(any(term.lower() in t or t in term.lower() for term in terms) for t in tags)

    def is_transit_or_meal(tags: List[str]) -> bool:
        # Matches both English (legacy) and Japanese (new LLM output) tag variants
        return row_has_any_tag(tags, [
            # English (legacy)
            "transit", "train", "plane", "meal", "lunch", "food",
            # Japanese
            "移動中", "電車", "飛行機", "食事", "昼食",
        ])

    work = df.copy()
    if work.empty:
        return work

    if "event_type" not in work.columns:
        work["event_type"] = work["folder"].apply(infer_event_type_from_folder)

    def select_for_one_group(group_df: pd.DataFrame, rules: Dict[str, Any]) -> pd.DataFrame:

        local = group_df.copy()

        # ===== Ensure columns =====
        for col, default in {
            "shot_type_tags":   [],
            "person_signature": "不明",   # was "unknown"
            "class_hint":       "不明",   # was "unknown"
            "day_hint":         "不明",   # was "unknown"
        }.items():
            if col not in local.columns:
                local[col] = [default for _ in range(len(local))]

        local["shot_type_tags_norm"]     = local["shot_type_tags"].apply(normalize_tags)
        local["event_relevance"]         = pd.to_numeric(local.get("event_relevance", 5), errors="coerce").fillna(5)
        local["target_grade_relevance"]  = pd.to_numeric(local.get("target_grade_relevance", 5), errors="coerce").fillna(5)
        local["is_transit_or_meal"]      = local["shot_type_tags_norm"].apply(is_transit_or_meal)

        df_ok = local[local["is_ng"] == False].copy()
        if df_ok.empty:
            return df_ok

        df_ok = df_ok.sort_values(
            ["event_relevance", "target_grade_relevance", "total_score"],
            ascending=False
        )

        selected_idx = []

        # ===== Tracking =====
        person_counts      = {}
        class_counts       = {}
        scene_counts       = {}
        composition_counts = {}
        burst_count        = 0

        # ===== Tunable thresholds =====
        MAX_SAME_PERSON      = MAX_REPEAT_SAME_PERSON
        MAX_SAME_CLASS       = 3
        MAX_SAME_SCENE       = 2
        MAX_SAME_COMPOSITION = 3
        MAX_BURST_ALLOWED    = 1

        def get_class_key(row):
            return normalize_class_hint(row.get("class_hint", "不明"))

        def get_class_members(row):
            class_key = get_class_key(row)
            # normalize_class_hint returns "unknown" for unrecognised values —
            # treat both "unknown" and "不明" as no-class
            if class_key in ("unknown", "不明"):
                return []
            return class_key.split("_")[1:]

        def get_scene_key(row):
            tags = "_".join(sorted(row["shot_type_tags_norm"]))
            return f"{row['event_type']}_{tags}_{get_class_key(row)}"

        def get_composition_key(row):
            return tuple(sorted(row["shot_type_tags_norm"]))

        def get_person_sig(row):
            sig = str(row.get("person_signature", "不明")).strip().lower()
            # Treat both legacy "unknown" and new "不明" as missing
            if sig in ("unknown", "不明"):
                sig = f"class_{get_class_key(row)}_face_{row['face_visible']}"
            return sig

        def can_pick(row, strict=True):
            nonlocal burst_count

            sig          = get_person_sig(row)
            class_members = get_class_members(row)
            scene_key    = get_scene_key(row)
            comp_key     = get_composition_key(row)

            # ===== Person repetition =====
            if strict and person_counts.get(sig, 0) >= MAX_SAME_PERSON:
                return False

            # ===== Class repetition =====
            if strict and any(class_counts.get(m, 0) >= MAX_SAME_CLASS for m in class_members):
                return False

            # ===== Scene duplication =====
            if strict and scene_counts.get(scene_key, 0) >= MAX_SAME_SCENE:
                return False

            # ===== Composition repetition =====
            if strict and composition_counts.get(comp_key, 0) >= MAX_SAME_COMPOSITION:
                return False

            # ===== Burst filtering =====
            if strict and row.get("has_burst", False):
                if burst_count >= MAX_BURST_ALLOWED:
                    return False

            # ===== Transit/meal constraint =====
            max_tm = rules.get("max_transit_or_meal")
            if max_tm is not None and row.get("is_transit_or_meal", False):
                current_tm = sum(1 for i in selected_idx if df_ok.loc[i, "is_transit_or_meal"])
                if current_tm >= max_tm:
                    return False

            return True

        def add_pick(idx, reason, strict=True):
            nonlocal burst_count

            if idx in selected_idx:
                return False

            row = df_ok.loc[idx]

            if not can_pick(row, strict=strict):
                return False

            selected_idx.append(idx)

            sig           = get_person_sig(row)
            class_members = get_class_members(row)
            scene_key     = get_scene_key(row)
            comp_key      = get_composition_key(row)

            person_counts[sig]  = person_counts.get(sig, 0) + 1
            for m in class_members:
                class_counts[m] = class_counts.get(m, 0) + 1
            scene_counts[scene_key]       = scene_counts.get(scene_key, 0) + 1
            composition_counts[comp_key]  = composition_counts.get(comp_key, 0) + 1

            if row.get("has_burst", False):
                burst_count += 1

            df_ok.loc[idx, "selection_reason"] = reason
            return True

        # =========================
        # 1) Required tags FIRST
        # =========================
        for group in rules.get("required_tag_groups", []):
            candidates = df_ok[df_ok["shot_type_tags_norm"].apply(
                lambda tags: row_has_any_tag(tags, group)
            )]
            for idx in candidates.index:
                if add_pick(idx, f"required: {'/'.join(group)}"):
                    break

        # =========================
        # 2) Landmark
        # =========================
        must_landmark = int(rules.get("must_have_landmark", 0) or 0)
        if must_landmark > 0:
            for idx in df_ok[df_ok["landmark_visible"] == True].index:
                if sum(df_ok.loc[i, "landmark_visible"] for i in selected_idx) >= must_landmark:
                    break
                add_pick(idx, "landmark")

        # =========================
        # 3) Cheering
        # =========================
        cheer_min, _ = rules.get("cheering_range", (0, 0))
        if cheer_min > 0:
            for idx in df_ok[df_ok["cheering_shot"] == True].index:
                if sum(df_ok.loc[i, "cheering_shot"] for i in selected_idx) >= cheer_min:
                    break
                add_pick(idx, "cheering")

        # =========================
        # 4) Ball visibility
        # =========================
        if rules.get("require_ball_visible", False):
            for idx in df_ok[df_ok["ball_visible"] == True].index:
                if any(df_ok.loc[i, "ball_visible"] for i in selected_idx):
                    break
                add_pick(idx, "ball")

        # =========================
        # 5) Balanced sampling
        # =========================
        balance_col = None
        if rules.get("balance_by_class", False):
            balance_col = "class_key"
        elif rules.get("balance_by_day", False):
            balance_col = "day_hint"

        if balance_col:
            if balance_col == "class_key":
                local["class_key"] = local["class_hint"].apply(normalize_class_hint)
                df_ok["class_key"] = df_ok["class_hint"].apply(normalize_class_hint)
            grouped = {}
            for idx, row in df_ok.iterrows():
                key = str(row.get(balance_col, "不明"))
                grouped.setdefault(key, []).append(idx)

            for key in grouped:
                grouped[key].sort(key=lambda i: df_ok.loc[i, "total_score"], reverse=True)

            while len(selected_idx) < MAX_FINAL_PHOTOS:
                changed = False
                for key in sorted(grouped.keys(), key=lambda k: len(grouped[k])):
                    if not grouped[key]:
                        continue
                    idx = grouped[key].pop(0)
                    if add_pick(idx, f"balanced:{balance_col}"):
                        changed = True
                    if len(selected_idx) >= MAX_FINAL_PHOTOS:
                        break
                if not changed:
                    break

        # =========================
        # 6) Fill remaining (STRICT)
        # =========================
        for idx in df_ok.index:
            if len(selected_idx) >= MAX_FINAL_PHOTOS:
                break
            add_pick(idx, "top", strict=True)

        # =========================
        # 7) SMART FALLBACK (RELAXED)
        # =========================
        if len(selected_idx) < MIN_FINAL_PHOTOS:
            for idx in df_ok.index:
                if len(selected_idx) >= MIN_FINAL_PHOTOS:
                    break
                add_pick(idx, "fallback_relaxed", strict=False)

        # =========================
        # 8) Fill up to MAX if needed
        # =========================
        if len(selected_idx) < MAX_FINAL_PHOTOS:
            for idx in df_ok.index:
                if len(selected_idx) >= MAX_FINAL_PHOTOS:
                    break
                add_pick(idx, "fill_to_max_relaxed", strict=False)

        selected_df = local.loc[selected_idx].copy() if selected_idx else df_ok.head(0).copy()

        if not selected_df.empty:
            selected_df = selected_df.sort_values("total_score", ascending=False)

        return selected_df

    selected_groups = []

    for folder_name, group_df in work.groupby("folder", dropna=False):
        inferred_event = infer_event_type_from_folder(folder_name)
        rules          = get_event_rules(inferred_event)
        picked         = select_for_one_group(group_df, rules)

        if not picked.empty:
            picked["event_type"] = inferred_event
            selected_groups.append(picked)

    if not selected_groups:
        print("選定対象の写真が見つかりませんでした（NG以外の写真なし）。")
        return work.head(0).copy()

    return pd.concat(selected_groups, ignore_index=False)


df_selected = select_best_by_threshold(df_results)
print(f"ベストショット {len(df_selected)} 枚を選定しました（イベント対応選定）。")
display(df_selected)

# =========================
# CELL 10) Export Results to Japanese Excel (All Photos: Selected / NG / Unselected)
# =========================

import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
import numpy as np

JP_COLUMNS = {
    "no":                           "No.",
    "file_name":                    "ファイル名",
    "folder":                       "フォルダ",
    "event_type":                   "イベント種別",
    "is_ng":                        "NG判定",
    "ng_reason":                    "NG理由",
    "technical_score":              "技術スコア",
    "expression_score":             "表情スコア",
    "composition_score":            "構図スコア",
    "rarity_score":                 "希少性スコア",
    "quality_score":                "品質スコア",
    "total_score":                  "総合スコア",
    "target_grade_relevance":       "対象学年関連度",
    "event_relevance":              "行事関連度",
    "blur_detected":                "ブレ検出",
    "exposure_issue":               "露出問題",
    "protagonist_eyes_closed":      "主役の目閉じ",
    "protagonist_imperfect_moment": "主役の失敗瞬間",
    "bystander_issue":              "周囲の目閉じ等",
    "eyes_closed":                  "目閉じ",
    "face_visible":                 "顔の視認性",
    "landmark_visible":             "ランドマーク有",
    "ball_visible":                 "ボール視認",
    "cheering_shot":                "応援シーン",
    "shot_type_tags":               "シーンタグ",
    "shot_type_tags_norm":          "シーンタグ（正規化）",
    "class_hint":                   "クラス推定",
    "class_key":                    "クラスキー",
    "day_hint":                     "日程推定",
    "person_signature":             "人物識別子",
    "has_burst":                    "連写フラグ",
    "has_similar_composition":      "類似構図フラグ",
    "has_duplicate_subject":        "被写体重複フラグ",
    "is_transit_or_meal":           "移動・食事フラグ",
    "redundancy_penalty":           "重複ペナルティ",
    "selection_reason":             "選定理由",
    "short_comment":                "コメント",
    "path":                         "ファイルパス",
}

BOOL_COLUMNS_JP = {
    "is_ng", "blur_detected", "protagonist_eyes_closed",
    "protagonist_imperfect_moment", "bystander_issue", "eyes_closed",
    "face_visible", "landmark_visible", "ball_visible", "cheering_shot",
    "has_burst", "has_similar_composition", "has_duplicate_subject",
    "is_transit_or_meal",
}

LIST_COLUMNS_JP = {"shot_type_tags", "shot_type_tags_norm"}


def jp_bool(val) -> str:
    if val is True or str(val).lower() in ("true", "1", "yes"):
        return "はい"
    if val is False or str(val).lower() in ("false", "0", "no"):
        return "いいえ"
    return str(val) if val is not None else ""


def coerce_to_excel(col: str, val) -> Any:
    if val is None:
        return ""
    try:
        if np.isnan(val):
            return ""
    except (TypeError, ValueError):
        pass

    if isinstance(val, np.integer):
        val = int(val)
    elif isinstance(val, np.floating):
        val = float(val)
    elif isinstance(val, np.bool_):
        val = bool(val)

    if col in BOOL_COLUMNS_JP:
        return jp_bool(val)

    if col in LIST_COLUMNS_JP or isinstance(val, (list, tuple)):
        if isinstance(val, (list, tuple)):
            return "、".join(str(t) for t in val)
        s = str(val).strip()
        if s.startswith("[") and s.endswith("]"):
            try:
                import ast
                parsed = ast.literal_eval(s)
                if isinstance(parsed, (list, tuple)):
                    return "、".join(str(t) for t in parsed)
            except Exception:
                pass
        return s

    if col in ("redundancy_penalty", "quality_score", "total_score"):
        try:
            return round(float(val), 3)
        except Exception:
            pass

    if not isinstance(val, (int, float, str, bool)):
        return str(val)

    return val


def _build_sheet(
    ws,
    df: pd.DataFrame,
    title: str,
    header_fill_hex: str = "1F4E79",
    row_fill_fn=None,
):
    all_cols = [c for c in JP_COLUMNS if c in df.columns]
    all_cols += [c for c in df.columns if c not in JP_COLUMNS]
    headers  = [JP_COLUMNS.get(c, c) for c in all_cols]

    HEADER_FILL = PatternFill("solid", fgColor=header_fill_hex)
    HEADER_FONT = Font(bold=True, color="FFFFFF", size=10)
    BODY_FONT   = Font(size=10)
    CENTRE      = Alignment(horizontal="center", vertical="center")
    LEFT        = Alignment(horizontal="left",   vertical="center")
    thin        = Side(style="thin", color="AAAAAA")
    BORDER      = Border(left=thin, right=thin, top=thin, bottom=thin)

    GREEN_FILL  = PatternFill("solid", fgColor="C6EFCE")
    YELLOW_FILL = PatternFill("solid", fgColor="FFEB9C")
    RED_FILL    = PatternFill("solid", fgColor="FFC7CE")

    for ci, hdr in enumerate(headers, start=1):
        cell           = ws.cell(row=1, column=ci, value=hdr)
        cell.fill      = HEADER_FILL
        cell.font      = HEADER_FONT
        cell.alignment = CENTRE
        cell.border    = BORDER

    for ri, (_, row) in enumerate(df[all_cols].iterrows(), start=2):
        custom_fill = row_fill_fn(row) if row_fill_fn else None
        for ci, col in enumerate(all_cols, start=1):
            val            = coerce_to_excel(col, row[col])
            cell           = ws.cell(row=ri, column=ci, value=val)
            cell.font      = BODY_FONT
            cell.border    = BORDER
            cell.alignment = CENTRE if col in BOOL_COLUMNS_JP or col == "no" else LEFT
            if custom_fill:
                cell.fill = custom_fill
            elif col == "total_score":
                try:
                    score = float(row["total_score"])
                    if score >= 7.0:
                        cell.fill = GREEN_FILL
                    elif score >= 5.0:
                        cell.fill = YELLOW_FILL
                    else:
                        cell.fill = RED_FILL
                except Exception:
                    pass

    ws.freeze_panes = "A2"

    for ci, col in enumerate(all_cols, start=1):
        max_len = len(headers[ci - 1])
        for ri_w in range(2, ws.max_row + 1):
            cv = ws.cell(row=ri_w, column=ci).value
            if cv:
                max_len = max(max_len, len(str(cv)))
        ws.column_dimensions[get_column_letter(ci)].width = min(max_len + 4, 40)


def export_all_results_japanese(
    df_all: pd.DataFrame,
    df_selected: pd.DataFrame,
    out_path: str,
) -> str:
    NG_ROW_FILL       = PatternFill("solid", fgColor="FFB3B3")
    UNSELECTED_FILL   = PatternFill("solid", fgColor="F2F2F2")

    # ── Derive subsets ────────────────────────────────────────────────────────
    df_ng = df_all[df_all["is_ng"] == True].copy()

    selected_paths = set(df_selected["path"].tolist()) if "path" in df_selected.columns else set()
    df_unselected  = df_all[
        (df_all["is_ng"] == False) &
        (~df_all["path"].isin(selected_paths))
    ].copy()

    # Add 'no' column to selected photos
    df_selected_sorted = df_selected.sort_values("total_score", ascending=False).copy()
    df_selected_sorted.insert(0, "no", range(1, len(df_selected_sorted) + 1))

    wb = openpyxl.Workbook()

    # ── Sheet 1: Best shots ───────────────────────────────────────────────────
    ws1       = wb.active
    ws1.title = "ベストショット一覧"
    _build_sheet(ws1, df_selected_sorted, "ベストショット一覧")

    # ── Sheet 2: NG photos ────────────────────────────────────────────────────
    ws2       = wb.create_sheet("NG写真一覧")
    _build_sheet(
        ws2, df_ng,
        "NG写真一覧",
        header_fill_hex="8B0000",
        row_fill_fn=lambda row: NG_ROW_FILL,
    )

    # ── Sheet 3: Non-selected (non-NG) photos ─────────────────────────────────
    ws3       = wb.create_sheet("未選定写真一覧")
    _build_sheet(
        ws3, df_unselected.sort_values("total_score", ascending=False),
        "未選定写真一覧",
        header_fill_hex="4A4A4A",
        row_fill_fn=lambda row: UNSELECTED_FILL,
    )

    # ── Sheet 4: Summary stats ────────────────────────────────────────────────
    ws4       = wb.create_sheet("統計サマリー")
    bold_font = Font(bold=True, size=10)

    def safe_sum(df, c):
        return int(df[c].sum()) if c in df.columns else "—"

    def safe_mean(df, c):
        return round(float(df[c].mean()), 2) if c in df.columns and len(df) > 0 else "—"

    sections = [
        ("■ 全体集計", None),
        ("総写真数（評価済み）",          len(df_all)),
        ("NG除外枚数",                    safe_sum(df_all, "is_ng")),
        ("選定枚数",                      len(df_selected)),
        ("未選定枚数（non-NG）",           len(df_unselected)),
        ("", None),
        ("■ 選定写真スコア平均", None),
        ("平均総合スコア",                safe_mean(df_selected, "total_score")),
        ("平均技術スコア",                safe_mean(df_selected, "technical_score")),
        ("平均表情スコア",                safe_mean(df_selected, "expression_score")),
        ("平均構図スコア",                safe_mean(df_selected, "composition_score")),
        ("平均希少性スコア",              safe_mean(df_selected, "rarity_score")),
        ("", None),
        ("■ 品質フラグ（全写真）", None),
        ("主役の目閉じ枚数",              safe_sum(df_all, "protagonist_eyes_closed")),
        ("周囲の目閉じ等（警告）枚数",    safe_sum(df_all, "bystander_issue")),
        ("連写フラグ付き枚数",            safe_sum(df_all, "has_burst")),
        ("ランドマーク有り枚数",          safe_sum(df_all, "landmark_visible")),
        ("応援シーン枚数",                safe_sum(df_all, "cheering_shot")),
    ]

    ws4.cell(row=1, column=1, value="項目").font = bold_font
    ws4.cell(row=1, column=2, value="値").font   = bold_font

    for ri, (label, val) in enumerate(sections, start=2):
        label_cell = ws4.cell(row=ri, column=1, value=label)
        if label.startswith("■"):
            label_cell.font = Font(bold=True, size=10)
            ws4.cell(row=ri, column=2, value="")
        elif val is not None:
            ws4.cell(row=ri, column=2, value=val)

    ws4.column_dimensions["A"].width = 36
    ws4.column_dimensions["B"].width = 16

    # Per-event breakdown
    if "event_type" in df_all.columns:
        offset = len(sections) + 4
        ws4.cell(row=offset, column=1, value="■ イベント種別別 枚数").font = bold_font
        ws4.cell(row=offset, column=2, value="選定").font = bold_font
        ws4.cell(row=offset, column=3, value="NG").font   = bold_font
        ws4.cell(row=offset, column=4, value="未選定").font = bold_font
        ws4.column_dimensions["C"].width = 10
        ws4.column_dimensions["D"].width = 10

        all_events = sorted(df_all["event_type"].dropna().unique())
        for i, etype in enumerate(all_events, start=1):
            sel_count = len(df_selected[df_selected["event_type"] == etype]) if "event_type" in df_selected.columns else 0
            ng_count  = len(df_ng[df_ng["event_type"] == etype])             if "event_type" in df_ng.columns       else 0
            un_count  = len(df_unselected[df_unselected["event_type"] == etype])
            ws4.cell(row=offset + i, column=1, value=etype)
            ws4.cell(row=offset + i, column=2, value=sel_count)
            ws4.cell(row=offset + i, column=3, value=ng_count)
            ws4.cell(row=offset + i, column=4, value=un_count)

    wb.save(out_path)
    print(f"Saved Japanese Excel (4 sheets): {out_path}")
    return out_path
```

# =========================
# CELL: 11 'Other' Passing Photos
# =========================
# Identify photos that passed the NG filter but were not selected

if 'df_results' in locals() and 'df_selected' in locals():
    selected_paths = set(df_selected['path'].tolist())
    df_others = df_results[
        (df_results['is_ng'] == False) &
        (~df_results['path'].isin(selected_paths))
    ].copy()

    print("Photos that passed quality check but were not selected:")
    if not df_others.empty:
        display(
            df_others[['file_name', 'total_score', 'short_comment']]
            .sort_values('total_score', ascending=False)
        )
    else:
        print("No other passing photos found.")
else:
    print("Dataframes not found. Please ensure Cells 7 and 9 have been executed.")

# =========================
# CELL 12) Display NG Photos Log
# =========================

df_ng = df_results[df_results["is_ng"] == True].copy()

print(f"\n{'='*60}")
print(f"NG PHOTO LOG ({len(df_ng)} photos)")
print(f"{'='*60}")

if len(df_ng) > 0:
    display(df_ng[[
        "file_name", "folder", "ng_reason",
        "blur_detected", "exposure_issue",
        "protagonist_eyes_closed",
        "bystander_issue",
    ]])
else:
    print("No NG photos found - all photos passed quality check!")

"""**Run this cell to save results to Google Drive**"""

# =========================
# CELL 13) Save Results to Excel and Copy Photos (Best, NG, & Others)
# =========================

def write_df_to_worksheet(ws, df: pd.DataFrame):
    if df is None or not isinstance(df, pd.DataFrame) or df.empty:
        return
    def _excel_safe(value: Any) -> Any:
        if isinstance(value, (list, dict, tuple, set)):
            return json.dumps(list(value) if isinstance(value, set) else value, ensure_ascii=False)
        return value
    for r in dataframe_to_rows(df, index=False, header=True):
        ws.append([_excel_safe(v) for v in r])


ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")

SELECTED_OUTPUT_DIR = os.path.join(OUTPUT_DIR, f"{ts}_best_photos")
NG_OUTPUT_DIR       = os.path.join(OUTPUT_DIR, f"{ts}_ng_photos")
OTHERS_OUTPUT_DIR   = os.path.join(OUTPUT_DIR, f"{ts}_other_passing_photos")

os.makedirs(SELECTED_OUTPUT_DIR, exist_ok=True)
os.makedirs(NG_OUTPUT_DIR,       exist_ok=True)
os.makedirs(OTHERS_OUTPUT_DIR,   exist_ok=True)


def ensure_event_output_dir(base_dir: str, event_type: str) -> str:
    event_dir = os.path.join(base_dir, normalize_event_type(event_type))
    os.makedirs(event_dir, exist_ok=True)
    return event_dir


if not df_selected.empty:
    df_selected = df_selected.sort_values(
        ["event_type", "total_score"], ascending=[True, False]
    )

# 1) Copy Selected Best Photos
rename_rows = []

if not df_selected.empty:
    for _, row in df_selected.iterrows():
        src_path   = row["path"]
        event_type = row.get("event_type", infer_event_type_from_folder(row.get("folder", "")))
        event_dir  = ensure_event_output_dir(SELECTED_OUTPUT_DIR, event_type)

        original_name = row["file_name"]
        stem, ext     = os.path.splitext(original_name)
        date_prefix   = get_file_date_string(src_path)
        new_name      = f"{date_prefix}_{stem}_{BEST_TOKEN}_{int(row['total_score'])}{ext}"

        if os.path.exists(src_path):
            dst_path = unique_path(os.path.join(event_dir, new_name))
            shutil.copy2(src_path, dst_path)
            rename_rows.append({
                "folder":             row["folder"],
                "event_type":         normalize_event_type(event_type),
                "original_file_name": original_name,
                "new_file_name":      os.path.basename(dst_path),
                "total_score":        row["total_score"],
                "selection_reason":   row.get("selection_reason", ""),
            })

# 2) Copy NG Photos
if not df_ng.empty:
    for _, row in df_ng.iterrows():
        src_path  = row["path"]
        event_dir = ensure_event_output_dir(
            NG_OUTPUT_DIR,
            row.get("event_type", infer_event_type_from_folder(row.get("folder", "")))
        )
        if os.path.exists(src_path):
            shutil.copy2(src_path, os.path.join(event_dir, row["file_name"]))

# 3) Copy Other Passing Photos
selected_paths = set(df_selected['path'].tolist()) if not df_selected.empty else set()
df_others = df_results[
    (df_results['is_ng'] == False) &
    (~df_results['path'].isin(selected_paths))
].copy()

if not df_others.empty:
    for _, row in df_others.iterrows():
        src_path  = row["path"]
        event_dir = ensure_event_output_dir(
            OTHERS_OUTPUT_DIR,
            row.get("event_type", infer_event_type_from_folder(row.get("folder", "")))
        )
        if os.path.exists(src_path):
            shutil.copy2(src_path, os.path.join(event_dir, row["file_name"]))

# Ensure event_type columns exist
if "event_type" not in df_results.columns:
    df_results["event_type"] = df_results["folder"].apply(infer_event_type_from_folder)
if not df_selected.empty and "event_type" not in df_selected.columns:
    df_selected["event_type"] = df_selected["folder"].apply(infer_event_type_from_folder)

# Event Summary + Balance Diagnostics
event_summary_rows = []

if not df_results.empty:
    for folder_name, group in df_results.groupby("folder", dropna=False):
        inferred_event = infer_event_type_from_folder(folder_name)
        sel_group      = df_selected[df_selected["folder"] == folder_name] if not df_selected.empty else pd.DataFrame()
        rules          = get_event_rules(inferred_event)

        event_summary_rows.append({
            "folder":                  folder_name,
            "event_type":              inferred_event,
            "total":                   len(group),
            "selected":                len(sel_group),
            "ng":                      int((group["is_ng"] == True).sum()),
            "must_have_landmark":      int(rules.get("must_have_landmark", 0) or 0),
            "landmark_selected":       int((sel_group.get("landmark_visible", pd.Series(dtype=bool)) == True).sum()) if not sel_group.empty else 0,
            "cheering_selected":       int((sel_group.get("cheering_shot",    pd.Series(dtype=bool)) == True).sum()) if not sel_group.empty else 0,
            "ball_visible_selected":   int((sel_group.get("ball_visible",     pd.Series(dtype=bool)) == True).sum()) if not sel_group.empty else 0,
            "unique_classes":          sel_group["class_hint"].nunique()       if not sel_group.empty else 0,
            "unique_days":             sel_group["day_hint"].nunique()         if not sel_group.empty else 0,
            "unique_persons":          sel_group["person_signature"].nunique() if not sel_group.empty else 0,
            "burst_count":             int(sel_group.get("has_burst",             pd.Series(dtype=bool)).sum()) if not sel_group.empty else 0,
            "duplicate_subject_count": int(sel_group.get("has_duplicate_subject", pd.Series(dtype=bool)).sum()) if not sel_group.empty else 0,
            "avg_total_score":         round(float(sel_group["total_score"].mean()), 2) if not sel_group.empty else 0,
        })

event_summary_df = pd.DataFrame(event_summary_rows)

if not event_summary_df.empty:
    def generate_warning(row):
        warnings = []
        if row["unique_classes"] <= 1 and row["selected"] > 3:
            warnings.append("low class diversity")
        if row["burst_count"] > 2:
            warnings.append("too many burst shots")
        if row["duplicate_subject_count"] > 2:
            warnings.append("same student repeated")
        return ", ".join(warnings)
    event_summary_df["warning"] = event_summary_df.apply(generate_warning, axis=1)

df_rename = pd.DataFrame(rename_rows)

# Standard Excel
excel_path = os.path.join(OUTPUT_DIR, f"{ts}_snap_photo_results.xlsx")

wb = Workbook()
wb.remove(wb.active)

sheets = [
    ("Summary", pd.DataFrame([{
        "total":           len(df_results),
        "event_type_mode": "per_folder_inference",
        "target_grade":    TARGET_GRADE if TARGET_GRADE else "not_set",
        "selected":        len(df_selected),
        "ng":              int((df_results["is_ng"] == True).sum()),
        "others":          len(df_others),
    }])),
    ("Event_Summary",  event_summary_df),
    ("NG_Log",         df_ng),
    ("Selected",       df_selected),
    ("Others",         df_others),
    ("Rename_Map",     df_rename),
]

for name, df in sheets:
    write_df_to_worksheet(wb.create_sheet(title=name), df)

wb.save(excel_path)

# Japanese Excel — filename constructed here, function just writes to it
japanese_excel_path = os.path.join(OUTPUT_DIR, f"{ts}_ベストショット.xlsx")
export_all_results_japanese(df_results, df_selected, japanese_excel_path)

print(f"Saved results to: {excel_path}")
print(f"Saved Japanese Excel to: {japanese_excel_path}")
print(f"Best: {SELECTED_OUTPUT_DIR}/<event_type>/")
print(f"NG: {NG_OUTPUT_DIR}/<event_type>/")
print(f"Others: {OTHERS_OUTPUT_DIR}/<event_type>/")

# =========================
# CELL 14) Save to Google Drive (Versioning)
# =========================

DRIVE_BASE_PARENT = "/content/drive/MyDrive/LTID/Photography_Pipeline/Snap Pictures Samples/Output/Best shot folders"
os.makedirs(DRIVE_BASE_PARENT, exist_ok=True)

existing_folders = [
    d for d in os.listdir(DRIVE_BASE_PARENT)
    if os.path.isdir(os.path.join(DRIVE_BASE_PARENT, d)) and d.startswith("v")
]

version_nums = [
    int(re.search(r'^v(\d+)', f).group(1))
    for f in existing_folders if re.search(r'^v(\d+)', f)
]

next_v           = max(version_nums) + 1 if version_nums else 1
DRIVE_OUTPUT_DIR = os.path.join(DRIVE_BASE_PARENT, f"v{next_v}")
os.makedirs(DRIVE_OUTPUT_DIR, exist_ok=True)

print(f"Target Version: v{next_v}")

# Copy both Excel files
for xls in [excel_path, japanese_excel_path]:
    if os.path.exists(xls):
        shutil.copy2(xls, os.path.join(DRIVE_OUTPUT_DIR, os.path.basename(xls)))
        print(f"Copied: {os.path.basename(xls)}")

# Sync photo folders
for src_dir, label in [
    (SELECTED_OUTPUT_DIR, "best_photos"),
    (NG_OUTPUT_DIR,       "ng_photos"),
    (OTHERS_OUTPUT_DIR,   "other_passing_photos"),
]:
    if os.path.exists(src_dir):
        shutil.copytree(src_dir, os.path.join(DRIVE_OUTPUT_DIR, label), dirs_exist_ok=True)

print(f"\nDrive sync to v{next_v} complete!")

# =========================
# CELL 12) Download Results (for Colab)
# =========================

# Uncomment to download files directly:
# files.download(excel_path)
# files.download(zip_path)

"""## Other"""

# =========================
# NEW CELL: Visual Verification
# =========================
# Run this after processing to see the images and scores together

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

def visualize_results(df, max_images=10):
    num_images = min(len(df), max_images)
    cols = 2
    rows = (num_images + 1) // cols

    plt.figure(figsize=(15, 5 * rows))
    for i, (_, row) in enumerate(df.head(num_images).iterrows()):
        plt.subplot(rows, cols, i + 1)
        img = mpimg.imread(row['path'])
        plt.imshow(img)
        color = 'red' if row['is_ng'] else 'green'
        title = f"File: {row['file_name']}\nScore: {row['total_score']:.2f} | NG: {row['is_ng']}\nReason: {row['ng_reason']}"
        plt.title(title, color=color, fontsize=10)
        plt.axis('off')
    plt.tight_layout()
    plt.show()

if 'df_results' in locals():
    print("Displaying top results for verification:")
    visualize_results(df_results.sort_values('total_score', ascending=False))
else:
    print("Please run the processing cell first.")